# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Apple Pay`. Hand-written extras go in lib/paystack_sdk/resources/extensions/apple_pay.rb.
# scaffold-digest: cd91bbd0850ed1baf4fd266d161cc41c75551ecff1190aa614ba064fddd10c7a

require_relative "base"

module PaystackSdk
  module Resources
    # Apple Pay operations.
    class ApplePay < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {next_cursor: "next", domain_name: "domainName"}.freeze

      # List Domains.
      #
      # Lists all registered domains on your integration.
      #
      # @param use_cursor [Boolean] A flag to indicate if cursor based pagination should be used
      # @param next_cursor [String] An alphanumeric value returned for every cursor based retrieval, used to retrieve the next set of data
      # @param previous [String] An alphanumeric value returned for every cursor based retrieval, used to retrieve the previous set of data
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/apple-pay/#list-domains
      def list_domains(use_cursor: nil, next_cursor: nil, previous: nil)
        wire_query = to_wire({use_cursor:, next_cursor:, previous:}, WIRE_NAMES)

        handle_response(@connection.get("/apple-pay/domain", wire_query))
      end

      # Register Domain.
      #
      # Register a top-level domain or subdomain for your Apple Pay integration.
      #
      # @param domain_name [String] The domain or subdomain for your application
      # @note Registers a domain for Apple Pay on the whole account. This changes Apple Pay
      #   configuration that may also affect live mode, even with a test key (sk_test_). Not
      #   verified against the live API by this SDK: do not call it to try the API out.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/apple-pay/#register-domain
      def register_domain(domain_name:)
        validate_presence!(value: domain_name, name: "domainName")

        wire_body = to_wire({domain_name:}, WIRE_NAMES)

        handle_response(@connection.post("/apple-pay/domain", wire_body))
      end

      # Unregister Domain.
      #
      # Unregister a top-level domain or subdomain previously used for your Apple Pay integration.
      #
      # @param domain_name [String] The domain or subdomain for your application
      # @note Unregisters a domain from Apple Pay on the whole account. This changes Apple Pay
      #   configuration that may also affect live mode, even with a test key (sk_test_). Not
      #   verified against the live API by this SDK, including how Paystack reads the request body
      #   of a DELETE.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/apple-pay/#unregister-domain
      def unregister_domain(domain_name:)
        validate_presence!(value: domain_name, name: "domainName")

        wire_body = to_wire({domain_name:}, WIRE_NAMES)

        handle_response(
          @connection.delete("/apple-pay/domain") { |request| request.body = wire_body }
        )
      end
    end
  end
end
