# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Balance`. Hand-written extras go in lib/paystack_sdk/resources/extensions/balances.rb.
# scaffold-digest: 65e146fbcd39c274107a8234988e1b3b51e3c58a5e74d7c4b0bf9c4f084a9b83

require_relative "base"

module PaystackSdk
  module Resources
    # Balance operations.
    class Balances < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # Fetch Balance.
      #
      # Fetch the available balance on your integration
      #
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transfer-control/#balance
      def fetch
        handle_response(@connection.get("/balance"))
      end

      # Balance Ledger.
      #
      # Fetch all pay-ins and pay-outs that occured on your integration
      #
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The section to retrieve
      # @param from [String] The start date
      # @param to [String] The end date
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transfer-control/#balance-ledger
      def ledger(per_page: nil, page: nil, from: nil, to: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire(
          {
            per_page:,
            page:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to")
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/balance/ledger", wire_query))
      end
    end
  end
end
