# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Bank`. Hand-written extras go in lib/paystack_sdk/resources/extensions/banks.rb.
# scaffold-digest: 530fc74fc57bba755180a37c395576bd9fc13c76500eae0fce6da7b1a6740ff9

require_relative "base"

module PaystackSdk
  module Resources
    # Bank operations.
    class Banks < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage", next_cursor: "next"}.freeze

      # List Banks.
      #
      # List banks supported on Paystack
      #
      # @param country [String] The country from which to obtain the list of supported banks One of: ghana, kenya, nigeria, south africa.
      # @param currency [String] The currency of the banks to list. One of: GHS, KES, NGN, ZAR, USD.
      # @param use_cursor [Boolean] A flag to indicate if cursor based pagination should be used
      # @param per_page [Integer] The number of records to fetch per request
      # @param page [Integer] The offset to retrieve data from
      # @param next_cursor [String] An alphanumeric value returned for every cursor based retrieval, used to retrieve the next set of data
      # @param previous [String] An alphanumeric value returned for every cursor based retrieval, used to retrieve the previous set of data
      # @param pay_with_bank_transfer [Boolean] A flag to filter for available banks a customer can make a transfer to complete a payment
      # @param pay_with_bank [Boolean] A flag to filter for banks a customer can pay directly from
      # @param enabled_for_verification [Boolean] A flag to filter the banks that are supported for account verification in South Africa.
      # @param gateway [String] The type of gateway for a Nigerian bank One of: emandate, digitalbankmandate.
      # @param type [String] Type of financial channel One of: ghipss, mobile_money, nuban, kepss, basa.
      # @param include_nip_sort_code [Boolean] A flag that returns Nigerian banks with their NIP institution code.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/miscellaneous/#bank
      def list(
        country: nil,
        currency: nil,
        use_cursor: nil,
        per_page: nil,
        page: nil,
        next_cursor: nil,
        previous: nil,
        pay_with_bank_transfer: nil,
        pay_with_bank: nil,
        enabled_for_verification: nil,
        gateway: nil,
        type: nil,
        include_nip_sort_code: nil
      )
        validate_allowed_values!(
          value: country,
          allowed_values: ["ghana", "kenya", "nigeria", "south africa"],
          name: "country"
        )
        validate_allowed_values!(
          value: currency,
          allowed_values: %w[GHS KES NGN ZAR USD],
          name: "currency"
        )
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")
        validate_allowed_values!(
          value: gateway,
          allowed_values: %w[emandate digitalbankmandate],
          name: "gateway"
        )
        validate_allowed_values!(
          value: type,
          allowed_values: %w[ghipss mobile_money nuban kepss basa],
          name: "type"
        )

        wire_query = to_wire(
          {
            country:,
            currency:,
            use_cursor:,
            per_page:,
            page:,
            next_cursor:,
            previous:,
            pay_with_bank_transfer:,
            pay_with_bank:,
            enabled_for_verification:,
            gateway:,
            type:,
            include_nip_sort_code:
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/bank", wire_query))
      end

      # Resolve Account Number.
      #
      # Resolve an account number to confirm the name associated with it
      #
      # @param account_number [String] The account number of interest
      # @param bank_code [String] The bank code associated with the account number
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/verification/#resolve-account
      def resolve_account_number(account_number:, bank_code:)
        validate_presence!(value: account_number, name: "account_number")
        validate_presence!(value: bank_code, name: "bank_code")

        wire_query = to_wire({account_number:, bank_code:}, WIRE_NAMES)

        handle_response(@connection.get("/bank/resolve", wire_query))
      end

      # Validate Bank Account.
      #
      # Confirm the authenticity of a customer's account number before sending money
      #
      # @param account_name [String] Customer's first and last name registered with their bank
      # @param account_number [String] Customer's account number
      # @param account_type [String] The type of the customer's account number One of: personal, business.
      # @param bank_code [String] The bank code of the customer’s bank.
      # @param country_code [String] The two digit ISO code of the customer’s bank
      # @param document_type [String] Customer’s mode of identity One of: identityNumber, passportNumber, businessRegistrationNumber.
      # @param document_number [String] Customer’s mode of identity number
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/verification/#validate-account
      def validate_account(
        account_name:,
        account_number:,
        account_type:,
        bank_code:,
        country_code:,
        document_type:,
        document_number: nil
      )
        validate_presence!(value: account_name, name: "account_name")
        validate_presence!(value: account_number, name: "account_number")
        validate_presence!(value: account_type, name: "account_type")
        validate_allowed_values!(
          value: account_type,
          allowed_values: %w[personal business],
          name: "account_type"
        )
        validate_presence!(value: bank_code, name: "bank_code")
        validate_presence!(value: country_code, name: "country_code")
        validate_presence!(value: document_type, name: "document_type")
        validate_allowed_values!(
          value: document_type,
          allowed_values: %w[identityNumber passportNumber businessRegistrationNumber],
          name: "document_type"
        )

        wire_body = to_wire(
          {
            account_name:,
            account_number:,
            account_type:,
            bank_code:,
            country_code:,
            document_type:,
            document_number:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/bank/validate", wire_body))
      end
    end
  end
end
