# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Bulk Charge`. Hand-written extras go in lib/paystack_sdk/resources/extensions/bulk_charges.rb.
# scaffold-digest: 37ac5fa2bfe1cd33e4f7ea6bb85671348dea9151f67bf30475dc69262c2ffbb9

require_relative "base"

module PaystackSdk
  module Resources
    # Bulk Charge operations.
    class BulkCharges < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Bulk Charge Batches.
      #
      # List all bulk charge batches.
      #
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The offset to retrieve data from
      # @param status [String] Filter by the status of the charges One of: active, paused, complete.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/bulk-charge/#list
      def list_batches(per_page: nil, page: nil, status: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")
        validate_allowed_values!(
          value: status,
          allowed_values: %w[active paused complete],
          name: "status"
        )

        wire_query = to_wire({per_page:, page:, status:}, WIRE_NAMES)

        handle_response(@connection.get("/bulkcharge", wire_query))
      end

      # Initiate Bulk Charge.
      #
      # Charge multiple customers in batches
      #
      # @param charges [Array] The request body: an array of hashes, each with authorization, amount, and optionally reference, attempt_partial_debit, at_least, metadata
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/bulk-charge/#initiate
      def initiate(charges:)
        validate_presence!(value: charges, name: "charges")

        handle_response(@connection.post("/bulkcharge", charges))
      end

      # Fetch Bulk Charge Batch.
      #
      # This endpoint retrieves a specific batch code.
      #
      # @param id_or_code [String] The code for the charge whose batches you want to retrieve
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/bulk-charge/#fetch-batch
      def fetch_batch(id_or_code:)
        validate_presence!(value: id_or_code, name: "id_or_code")

        handle_response(
          @connection.get("/bulkcharge/#{escape_path(id_or_code, name: "id_or_code")}")
        )
      end

      # List Charges in a Batch.
      #
      # This endpoint retrieves the charges associated with a specified batch code
      #
      # @param id_or_code [String] An code for the batch whose charges you want to retrieve
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The offset to retrieve data from
      # @param status [String] Filter by the status of the charges One of: success, failed, pending, error, inactive_authorization.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/bulk-charge/#fetch-charge
      def fetch_charges(id_or_code:, per_page: nil, page: nil, status: nil)
        validate_presence!(value: id_or_code, name: "id_or_code")
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")
        validate_allowed_values!(
          value: status,
          allowed_values: %w[success failed pending error inactive_authorization],
          name: "status"
        )

        wire_query = to_wire({per_page:, page:, status:}, WIRE_NAMES)

        handle_response(
          @connection.get("/bulkcharge/#{escape_path(id_or_code, name: "id_or_code")}/charges", wire_query)
        )
      end

      # Pause Bulk Charge Batch.
      #
      # Pause the processing of a charge batch
      #
      # @param batch_code [String] The batch code for the bulk charge you want to pause
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/bulk-charge/#pause
      def pause_batch(batch_code:)
        validate_presence!(value: batch_code, name: "batch_code")

        handle_response(
          @connection.get("/bulkcharge/pause/#{escape_path(batch_code, name: "batch_code")}")
        )
      end

      # Resume Bulk Charge Batch.
      #
      # Resume the processing of a previously paused charge batch
      #
      # @param batch_code [String] The batch code for the bulk charge you want to pause
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/bulk-charge/#resume
      def resume_batch(batch_code:)
        validate_presence!(value: batch_code, name: "batch_code")

        handle_response(
          @connection.get("/bulkcharge/resume/#{escape_path(batch_code, name: "batch_code")}")
        )
      end
    end
  end
end
