# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Charge`. Hand-written extras go in lib/paystack_sdk/resources/extensions/charges.rb.
# scaffold-digest: 8744e957871c8477379f6dc1389cc1e79df5884a4e594936b9ce64ffb6907ef2

require_relative "base"
require_relative "extensions/charges"

module PaystackSdk
  module Resources
    # Charge operations.
    class Charges < PaystackSdk::Resources::Base
      include Extensions::Charges

      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {}.freeze

      # Create Charge.
      #
      # Initiate a payment by integrating the payment channel of your choice.
      #
      # @param email [String] Customer's email address
      # @param amount [Integer] Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR
      # @param authorization_code [String] An authorization code to charge.
      # @param pin [String] 4-digit PIN (send with a non-reusable authorization code)
      # @param reference [String] Unique transaction reference.
      # @param birthday [String] The customer's birthday in the format YYYY-MM-DD e.g 2017-05-16
      # @param device_id [String] This is the unique identifier of the device a user uses in making payment.
      # @param metadata [Hash] JSON object of custom data
      # @param bank [Hash] The bank object if charging a bank account
      # @param mobile_money [Hash] Details of the mobile service provider
      # @param ussd [Hash] The USSD code for the provider to charge
      # @param eft [Hash] Details of the EFT provider
      # @param currency [String] The currency to charge in (GHS, KES and so on); Paystack uses your integration's currency when it is left out.
      # @param split_code [String] The split code (SPL_...) of a previously created split.
      # @param subaccount [String] The code (ACCT_...) of the subaccount that owns the payment.
      # @param bank_transfer [Hash] Settings for the Pay with Transfer and Pesalink channel (account_expires_at, the expiry time of the account).
      # @param qr [Hash] The QR provider details (provider, scan-to-pay being the only one); South Africa only.
      # @param capitec_pay [Hash] The Capitec Pay account holder (identifier_key, one of CELLPHONE, IDNUMBER or ACCOUNTNUMBER, and identifier_value); South Africa only.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/charge/#create
      def create(
        email:,
        amount:,
        authorization_code: nil,
        pin: nil,
        reference: nil,
        birthday: nil,
        device_id: nil,
        metadata: nil,
        bank: nil,
        mobile_money: nil,
        ussd: nil,
        eft: nil,
        currency: nil,
        split_code: nil,
        subaccount: nil,
        bank_transfer: nil,
        qr: nil,
        capitec_pay: nil
      )
        validate_presence!(value: email, name: "email")
        validate_email!(email: email, name: "email")
        validate_presence!(value: amount, name: "amount")
        validate_positive_integer!(value: amount, name: "amount")
        validate_reference_format!(reference: reference, name: "reference") unless reference.nil?

        wire_body = to_wire(
          {
            email:,
            amount:,
            authorization_code:,
            pin:,
            reference:,
            birthday: format_date(birthday, name: "birthday"),
            device_id:,
            metadata:,
            bank:,
            mobile_money:,
            ussd:,
            eft:,
            currency:,
            split_code:,
            subaccount:,
            bank_transfer:,
            qr:,
            capitec_pay:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/charge", wire_body))
      end

      # Submit PIN.
      #
      # Submit PIN to continue a charge
      #
      # @param pin [String] Customer's PIN for the ongoing transaction
      # @param reference [String] Transaction reference that requires the PIN
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/charge/#submit-pin
      def submit_pin(pin:, reference:)
        validate_presence!(value: pin, name: "pin")
        validate_presence!(value: reference, name: "reference")
        validate_reference_format!(reference: reference, name: "reference")

        wire_body = to_wire({pin:, reference:}, WIRE_NAMES)

        handle_response(@connection.post("/charge/submit_pin", wire_body))
      end

      # Submit OTP.
      #
      # Submit OTP to complete a charge
      #
      # @param otp [String] Customer's OTP for ongoing transaction
      # @param reference [String] The reference of the ongoing transaction
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/charge/#submit-otp
      def submit_otp(otp:, reference:)
        validate_presence!(value: otp, name: "otp")
        validate_presence!(value: reference, name: "reference")
        validate_reference_format!(reference: reference, name: "reference")

        wire_body = to_wire({otp:, reference:}, WIRE_NAMES)

        handle_response(@connection.post("/charge/submit_otp", wire_body))
      end

      # Submit Phone.
      #
      # Submit phone number when requested
      #
      # @param phone [String] Customer's mobile number
      # @param reference [String] The reference of the ongoing transaction
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/charge/#submit-phone
      def submit_phone(phone:, reference:)
        validate_presence!(value: phone, name: "phone")
        validate_presence!(value: reference, name: "reference")
        validate_reference_format!(reference: reference, name: "reference")

        wire_body = to_wire({phone:, reference:}, WIRE_NAMES)

        handle_response(@connection.post("/charge/submit_phone", wire_body))
      end

      # Submit Birthday.
      #
      # Submit the customer's birthday when requested
      #
      # @param birthday [String] Customer's birthday in the format YYYY-MM-DD e.g 2016-09-21
      # @param reference [String] The reference of the ongoing transaction
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/charge/#submit-birthday
      def submit_birthday(birthday:, reference:)
        validate_presence!(value: birthday, name: "birthday")
        validate_presence!(value: reference, name: "reference")
        validate_reference_format!(reference: reference, name: "reference")

        wire_body = to_wire(
          {
            birthday: format_date(birthday, name: "birthday"),
            reference:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/charge/submit_birthday", wire_body))
      end

      # Submit Address.
      #
      # Send the details of the customer's address for address verification
      #
      # @param address [String] Customer's address
      # @param city [String] Customer's city
      # @param state [String] Customer's state
      # @param zip_code [String] Customer's zipcode
      # @param reference [String] The reference of the ongoing transaction
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/charge/#submit-address
      def submit_address(address:, city:, state:, zip_code:, reference:)
        validate_presence!(value: address, name: "address")
        validate_presence!(value: city, name: "city")
        validate_presence!(value: state, name: "state")
        validate_presence!(value: zip_code, name: "zip_code")
        validate_presence!(value: reference, name: "reference")
        validate_reference_format!(reference: reference, name: "reference")

        wire_body = to_wire({address:, city:, state:, zip_code:, reference:}, WIRE_NAMES)

        handle_response(@connection.post("/charge/submit_address", wire_body))
      end

      # Check pending charge.
      #
      # When you get `pending` as a charge status or if there was an exception when calling any of the `/charge` endpoints, wait 10 seconds or more, then make a check to see if its status has changed.
      #
      # @param reference [String] The reference of the ongoing transaction
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/charge/#check
      def check_pending(reference:)
        validate_presence!(value: reference, name: "reference")

        handle_response(@connection.get("/charge/#{escape_path(reference, name: "reference")}"))
      end
    end
  end
end
