# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Customer`. Hand-written extras go in lib/paystack_sdk/resources/extensions/customers.rb.
# scaffold-digest: f23af37740665b121f36ec65dd45f1275b9b4358e704cf85b43f6cdd3218adae

require_relative "base"

module PaystackSdk
  module Resources
    # Customer operations.
    class Customers < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {next_cursor: "next", per_page: "perPage"}.freeze

      # List Customers.
      #
      # List customers on your integration
      #
      # @param use_cursor [Boolean] A flag to indicate if cursor based pagination should be used
      # @param next_cursor [String] An alphanumeric value returned for every cursor based retrieval, used to retrieve the next set of data
      # @param previous [String] An alphanumeric value returned for every cursor based retrieval, used to retrieve the previous set of data
      # @param from [String] The start date
      # @param to [String] The end date
      # @param per_page [Integer] The number of records to fetch per request
      # @param page [Integer] The offset to retrieve data from
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#list
      def list(
        use_cursor: nil,
        next_cursor: nil,
        previous: nil,
        from: nil,
        to: nil,
        per_page: nil,
        page: nil
      )
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire(
          {
            use_cursor:,
            next_cursor:,
            previous:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to"),
            per_page:,
            page:
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/customer", wire_query))
      end

      # Create Customer.
      #
      # Create a customer on your integration
      #
      # @param email [String] Customer's email address
      # @param first_name [String] Customer's first name
      # @param last_name [String] Customer's last name
      # @param phone [String] Customer's phone number
      # @param metadata [Hash] A set of key/value pairs that you can attach to the customer.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#create
      def create(email:, first_name: nil, last_name: nil, phone: nil, metadata: nil)
        validate_presence!(value: email, name: "email")
        validate_email!(email: email, name: "email")

        wire_body = to_wire({email:, first_name:, last_name:, phone:, metadata:}, WIRE_NAMES)

        handle_response(@connection.post("/customer", wire_body))
      end

      # Fetch Customer.
      #
      # Get details of a customer on your integration.
      #
      # @param email_or_code [String] The code for the customer gotten from the response of the customer creation
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#fetch
      def fetch(email_or_code:)
        validate_presence!(value: email_or_code, name: "email_or_code")

        handle_response(
          @connection.get("/customer/#{escape_path(email_or_code, name: "email_or_code")}")
        )
      end

      # Update Customer.
      #
      # Update a customer's details on your integration
      #
      # @param code [String] The code for the customer gotten from the response of the customer creation
      # @param first_name [String] Customer's first name
      # @param last_name [String] Customer's last name
      # @param phone [String] Customer's phone number
      # @param metadata [Hash] A set of key/value pairs that you can attach to the customer.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#update
      def update(code:, first_name: nil, last_name: nil, phone: nil, metadata: nil)
        validate_presence!(value: code, name: "code")

        wire_body = to_wire({first_name:, last_name:, phone:, metadata:}, WIRE_NAMES)

        handle_response(@connection.put("/customer/#{escape_path(code, name: "code")}", wire_body))
      end

      # Set Risk Action.
      #
      # Set customer's risk action by whitelisting or blacklisting the customer
      #
      # @param customer [String] The customer code from the response of the customer creation
      # @param risk_action [String] This determines the fraud rules that should be applied to the customer One of: allow, deny, default.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#whitelist-blacklist
      def set_risk_action(customer:, risk_action: nil)
        validate_presence!(value: customer, name: "customer")
        validate_allowed_values!(
          value: risk_action,
          allowed_values: %w[allow deny default],
          name: "risk_action"
        )

        wire_body = to_wire({customer:, risk_action:}, WIRE_NAMES)

        handle_response(@connection.post("/customer/set_risk_action", wire_body))
      end

      # Validate Customer.
      #
      # Validate a customer's identity
      #
      # @param code [String] The code for the customer gotten from the response of the customer creation
      # @param first_name [String] Customer's first name
      # @param last_name [String] Customer's last name
      # @param type [String] Predefined types of identification.
      # @param country [String] Two-letter country code of identification issuer
      # @param bvn [String] Customer's Bank Verification Number
      # @param bank_code [String] You can get the list of bank codes by calling the List Banks endpoint (https://api.paystack.co/bank).
      # @param account_number [String] Customer's bank account number.
      # @param middle_name [String] Customer's middle name
      # @param value [String] Customer's identification number.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#validate
      def validate(
        code:,
        first_name:,
        last_name:,
        type:,
        country:,
        bvn:,
        bank_code:,
        account_number:,
        middle_name: nil,
        value: nil
      )
        validate_presence!(value: code, name: "code")
        validate_presence!(value: first_name, name: "first_name")
        validate_presence!(value: last_name, name: "last_name")
        validate_presence!(value: type, name: "type")
        validate_presence!(value: country, name: "country")
        validate_presence!(value: bvn, name: "bvn")
        validate_presence!(value: bank_code, name: "bank_code")
        validate_presence!(value: account_number, name: "account_number")

        wire_body = to_wire(
          {
            first_name:,
            last_name:,
            type:,
            country:,
            bvn:,
            bank_code:,
            account_number:,
            middle_name:,
            value:
          },
          WIRE_NAMES
        )

        handle_response(
          @connection.post("/customer/#{escape_path(code, name: "code")}/identification", wire_body)
        )
      end

      # Initialize Authorization.
      #
      # Initiate a request to create a reusable authorization code for recurring transactions
      #
      # @param email [String] Customer's email address
      # @param channel [String] direct_debit is the only supported option for now One of: direct_debit.
      # @param callback_url [String] Fully qualified url (e.g.
      # @param account [Hash]
      # @param address [Hash]
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#initialize-authorization
      def initialize_authorization(email:, channel:, callback_url: nil, account: nil, address: nil)
        validate_presence!(value: email, name: "email")
        validate_email!(email: email, name: "email")
        validate_presence!(value: channel, name: "channel")
        validate_allowed_values!(value: channel, allowed_values: %w[direct_debit], name: "channel")

        wire_body = to_wire({email:, channel:, callback_url:, account:, address:}, WIRE_NAMES)

        handle_response(@connection.post("/customer/authorization/initialize", wire_body))
      end

      # Verify Authorization.
      #
      # Check the status of an authorization request
      #
      # @param reference [String] The reference returned in the initialization response
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#verify-authorization
      def verify_authorization(reference:)
        validate_presence!(value: reference, name: "reference")

        handle_response(
          @connection.get("/customer/authorization/verify/#{escape_path(reference, name: "reference")}")
        )
      end

      # Deactivate Authorization.
      #
      # Deactivate an authorization for any payment channel.
      #
      # @param authorization_code [String] Authorization code to be deactivated
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#deactivate-authorization
      def deactivate_authorization(authorization_code:)
        validate_presence!(value: authorization_code, name: "authorization_code")

        wire_body = to_wire({authorization_code:}, WIRE_NAMES)

        handle_response(@connection.post("/customer/authorization/deactivate", wire_body))
      end

      # Initialize Direct Debit.
      #
      # Initialize the process of linking an account to a customer for Direct Debit transactions
      #
      # @param id [Integer] The ID of the customer to initialize the direct debit for
      # @param account [Hash]
      # @param address [Hash]
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#initialize-direct-debit
      def initialize_direct_debit(id:, account:, address:)
        validate_presence!(value: id, name: "id")
        validate_presence!(value: account, name: "account")
        validate_presence!(value: address, name: "address")

        wire_body = to_wire({account:, address:}, WIRE_NAMES)

        handle_response(
          @connection.post("/customer/#{escape_path(id, name: "id")}/initialize-direct-debit", wire_body)
        )
      end

      # Direct Debit Activation Charge.
      #
      # Trigger an activation charge on an inactive mandate on behalf of your customer
      #
      # @param id [Integer] The customer ID attached to the authorization
      # @param authorization_id [Integer] The authorization ID gotten from the initiation response
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#directdebit-activation-charge
      def direct_debit_activation_charge(id:, authorization_id:)
        validate_presence!(value: id, name: "id")
        validate_presence!(value: authorization_id, name: "authorization_id")
        validate_numeric_id!(value: authorization_id, name: "authorization_id", allow_nil: false)

        wire_body = to_wire({authorization_id:}, WIRE_NAMES)

        handle_response(
          @connection.put("/customer/#{escape_path(id, name: "id")}/directdebit-activation-charge", wire_body)
        )
      end

      # Fetch Mandate Authorizations.
      #
      # Get the list of direct debit mandates associated with a customer
      #
      # @param id [Integer] The customer ID for the authorizations to fetch
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/customer/#directdebit-mandate-authorizations
      def fetch_mandate_authorizations(id:)
        validate_presence!(value: id, name: "id")

        handle_response(
          @connection.get("/customer/#{escape_path(id, name: "id")}/directdebit-mandate-authorizations")
        )
      end
    end
  end
end
