# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Dedicated Virtual Account`. Hand-written extras go in lib/paystack_sdk/resources/extensions/dedicated_virtual_accounts.rb.
# scaffold-digest: ced1a6e3ff1b259142646259b38808d9036c73b57ea1a30384a5f2ad8c7c4da5

require_relative "base"

module PaystackSdk
  module Resources
    # Dedicated Virtual Account operations.
    class DedicatedVirtualAccounts < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Dedicated Accounts.
      #
      # List dedicated virtual accounts available on your integration.
      #
      # @param active [Boolean] Status of the dedicated virtual account
      # @param customer [Integer] The customer's ID
      # @param currency [String] The currency of the dedicated virtual account One of: NGN, GHS.
      # @param provider_slug [String] The bank's slug in lowercase, without spaces
      # @param bank_id [String] The bank's ID
      # @param per_page [Integer] The number of records to fetch per request
      # @param page [Integer] The offset to retrieve data from
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dedicated-virtual-account/#list
      def list(
        active: nil,
        customer: nil,
        currency: nil,
        provider_slug: nil,
        bank_id: nil,
        per_page: nil,
        page: nil
      )
        validate_allowed_values!(value: currency, allowed_values: %w[NGN GHS], name: "currency")
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire(
          {
            active:,
            customer:,
            currency:,
            provider_slug:,
            bank_id:,
            per_page:,
            page:
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/dedicated_account", wire_query))
      end

      # Create Dedicated Account.
      #
      # Create a dedicated virtual account for an existing customer
      #
      # @param customer [String] The code for the previously created customer
      # @param preferred_bank [String] The bank slug for preferred bank.
      # @param subaccount [String] Subaccount code of the account you want to split the transaction with
      # @param split_code [String] Split code consisting of the lists of accounts you want to split the transaction with
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dedicated-virtual-account/#create
      def create(customer:, preferred_bank: nil, subaccount: nil, split_code: nil)
        validate_presence!(value: customer, name: "customer")

        wire_body = to_wire({customer:, preferred_bank:, subaccount:, split_code:}, WIRE_NAMES)

        handle_response(@connection.post("/dedicated_account", wire_body))
      end

      # Assign Dedicated Account.
      #
      # With this endpoint, you can create a customer, validate the customer, and assign a DVA to the customer.
      #
      # @param email [String] Customer's email address
      # @param first_name [String] Customer's first name
      # @param last_name [String] Customer's last name
      # @param phone [String] Customer's phone name
      # @param preferred_bank [String] The bank slug for preferred bank.
      # @param country [String] The two letter code country One of: NG, GH.
      # @param account_number [String] Customer's account number
      # @param bvn [String] Customer's Bank Verification Number
      # @param bank_code [String] Customer's bank code
      # @param subaccount [String] Subaccount code of the account you want to split the transaction with
      # @param split_code [String] Split code consisting of the lists of accounts you want to split the transaction with
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dedicated-virtual-account/#assign
      def assign(
        email:,
        first_name:,
        last_name:,
        phone:,
        preferred_bank:,
        country:,
        account_number: nil,
        bvn: nil,
        bank_code: nil,
        subaccount: nil,
        split_code: nil
      )
        validate_presence!(value: email, name: "email")
        validate_email!(email: email, name: "email")
        validate_presence!(value: first_name, name: "first_name")
        validate_presence!(value: last_name, name: "last_name")
        validate_presence!(value: phone, name: "phone")
        validate_presence!(value: preferred_bank, name: "preferred_bank")
        validate_presence!(value: country, name: "country")
        validate_allowed_values!(value: country, allowed_values: %w[NG GH], name: "country")

        wire_body = to_wire(
          {
            email:,
            first_name:,
            last_name:,
            phone:,
            preferred_bank:,
            country:,
            account_number:,
            bvn:,
            bank_code:,
            subaccount:,
            split_code:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/dedicated_account/assign", wire_body))
      end

      # Fetch Dedicated Account.
      #
      # Get details of a dedicated virtual account on your integration.
      #
      # @param dedicated_account_id [String] ID of dedicated virtual account
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dedicated-virtual-account/#fetch
      def fetch(dedicated_account_id:)
        validate_presence!(value: dedicated_account_id, name: "dedicated_account_id")

        handle_response(
          @connection.get("/dedicated_account/#{escape_path(dedicated_account_id, name: "dedicated_account_id")}")
        )
      end

      # Deactivate Dedicated Account.
      #
      # Deactivate a dedicated virtual account on your integration.
      #
      # @param dedicated_account_id [String] ID of dedicated virtual account
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dedicated-virtual-account/#deactivate
      def deactivate(dedicated_account_id:)
        validate_presence!(value: dedicated_account_id, name: "dedicated_account_id")

        handle_response(
          @connection.delete("/dedicated_account/#{escape_path(dedicated_account_id, name: "dedicated_account_id")}")
        )
      end

      # Requery Dedicated Account.
      #
      # Requery Dedicated Virtual Account for new transactions
      #
      # @param account_number [String] Virtual account number to requery
      # @param provider_slug [String] The bank's slug in lowercase, without spaces.
      # @param date [String] The day the transfer was made
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dedicated-virtual-account/#requery
      def requery(account_number: nil, provider_slug: nil, date: nil)
        wire_query = to_wire(
          {
            account_number:,
            provider_slug:,
            date: format_datetime(date, name: "date")
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/dedicated_account/requery", wire_query))
      end

      # Split Dedicated Account Transaction.
      #
      # Split a dedicated virtual account transaction with one or more accounts
      #
      # @param account_number [String] Valid Dedicated virtual account
      # @param subaccount [String] Subaccount code of the account you want to split the transaction with
      # @param split_code [String] Split code consisting of the lists of accounts you want to split the transaction with
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dedicated-virtual-account/#add-split
      def add_split(account_number:, subaccount: nil, split_code: nil)
        validate_presence!(value: account_number, name: "account_number")

        wire_body = to_wire({account_number:, subaccount:, split_code:}, WIRE_NAMES)

        handle_response(@connection.post("/dedicated_account/split", wire_body))
      end

      # Remove Split from Dedicated Account.
      #
      # If you've previously set up split payment for transactions on a dedicated virtual account, you can remove it with this endpoint
      #
      # @param account_number [String] Valid Dedicated virtual account
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dedicated-virtual-account/#remove-split
      def remove_split(account_number:)
        validate_presence!(value: account_number, name: "account_number")

        wire_body = to_wire({account_number:}, WIRE_NAMES)

        handle_response(
          @connection.delete("/dedicated_account/split") { |request| request.body = wire_body }
        )
      end

      # Fetch Bank Providers.
      #
      # Get available bank providers for a dedicated virtual account
      #
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dedicated-virtual-account/#providers
      def fetch_bank_providers
        handle_response(@connection.get("/dedicated_account/available_providers"))
      end
    end
  end
end
