# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Direct Debit`. Hand-written extras go in lib/paystack_sdk/resources/extensions/direct_debits.rb.
# scaffold-digest: 481405483446315741944cfcc9fecdadc3da399105e39d724083c79c03e6a510

require_relative "base"

module PaystackSdk
  module Resources
    # Direct Debit operations.
    class DirectDebits < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {}.freeze

      # Trigger Activation Charge.
      #
      # Trigger activation charge for specified customers
      #
      # @param customer_ids [Array] Array of customer IDs to trigger activation charge for
      # @note Charges the bank accounts behind the given customers' pending mandates to activate
      #   them; in live mode this moves real money. It was not called against the test API while
      #   this method was built, so its behaviour is documented, not verified. For one customer's
      #   inactive mandate, `customers.direct_debit_activation_charge` takes an `authorization_id`
      #   instead.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/directdebit/#activation-charge
      def trigger_activation_charge(customer_ids:)
        validate_presence!(value: customer_ids, name: "customer_ids")

        wire_body = to_wire({customer_ids:}, WIRE_NAMES)

        handle_response(@connection.put("/directdebit/activation-charge", wire_body))
      end

      # List Mandate Authorizations.
      #
      # Get a list of all the direct debit mandates on your integration
      #
      # @param cursor [String] The cursor value of the next set of authorizations to fetch.
      # @param status [String] Filter by the authorization status One of: pending, active, revoked.
      # @param per_page [Integer] The number of authorizations to fetch per request
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/directdebit/#mandate-authorizations
      def list_mandate_authorizations(cursor: nil, status: nil, per_page: nil)
        validate_allowed_values!(
          value: status,
          allowed_values: %w[pending active revoked],
          name: "status"
        )
        validate_positive_integer!(value: per_page, name: "per_page")

        wire_query = to_wire({cursor:, status:, per_page:}, WIRE_NAMES)

        handle_response(@connection.get("/directdebit/mandate-authorizations", wire_query))
      end
    end
  end
end
