# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Dispute`. Hand-written extras go in lib/paystack_sdk/resources/extensions/disputes.rb.
# scaffold-digest: 4d21cf962908ea0d724baff713ce71427be21015014886479ba0b6ecc2785dbe

require_relative "base"

module PaystackSdk
  module Resources
    # Dispute operations.
    class Disputes < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Disputes.
      #
      # List transaction disputes filed by customers
      #
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The section to retrieve
      # @param status [String] Dispute status One of: awaiting-merchant-feedback, awaiting-bank-feedback, pending, resolved.
      # @param transaction [String] Transaction ID
      # @param from [String] The start date
      # @param to [String] The end date
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dispute/#list
      def list(per_page: nil, page: nil, status: nil, transaction: nil, from: nil, to: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")
        validate_allowed_values!(
          value: status,
          allowed_values: %w[awaiting-merchant-feedback awaiting-bank-feedback pending resolved],
          name: "status"
        )

        wire_query = to_wire(
          {
            per_page:,
            page:,
            status:,
            transaction:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to")
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/dispute", wire_query))
      end

      # Fetch Dispute.
      #
      # Fetch a transaction dispute
      #
      # @param id [Integer] The unique identifier of the dispute
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dispute/#fetch
      def fetch(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/dispute/#{escape_path(id, name: "id")}"))
      end

      # Update Dispute.
      #
      # Update a transaction dispute
      #
      # @param id [Integer] The unique identifier of the dispute
      # @param refund_amount [Integer] The amount to refund, in the subunit of your currency
      # @param uploaded_filename [String] Filename of attachment returned via response from the Dispute upload URL
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dispute/#update
      def update(id:, refund_amount:, uploaded_filename: nil)
        validate_presence!(value: id, name: "id")
        validate_presence!(value: refund_amount, name: "refund_amount")

        wire_body = to_wire({refund_amount:, uploaded_filename:}, WIRE_NAMES)

        handle_response(@connection.put("/dispute/#{escape_path(id, name: "id")}", wire_body))
      end

      # Fetch Upload URL.
      #
      # Get the URL to upload a dispute evidence
      #
      # @param id [Integer] The unique identifier of the dispute
      # @param upload_filename [String] The file name, with its extension, that you want to upload (for example filename.pdf).
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dispute/#upload-url
      def fetch_upload_url(id:, upload_filename: nil)
        validate_presence!(value: id, name: "id")

        wire_query = to_wire({upload_filename:}, WIRE_NAMES)

        handle_response(
          @connection.get("/dispute/#{escape_path(id, name: "id")}/upload_url", wire_query)
        )
      end

      # Export Disputes.
      #
      # Export the disputes available on your integration
      #
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The section to retrieve
      # @param status [String] One of: awaiting-merchant-feedback, awaiting-bank-feedback, pending, resolved.
      # @param from [String] The start date
      # @param to [String] The end date
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dispute/#export
      def export(per_page: nil, page: nil, status: nil, from: nil, to: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")
        validate_allowed_values!(
          value: status,
          allowed_values: %w[awaiting-merchant-feedback awaiting-bank-feedback pending resolved],
          name: "status"
        )

        wire_query = to_wire(
          {
            per_page:,
            page:,
            status:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to")
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/dispute/export", wire_query))
      end

      # List Transaction Disputes.
      #
      # List all disputes filed for a transaction
      #
      # @param id [Integer] The unique identifier of the transaction
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dispute/#transaction
      def list_transaction(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/dispute/transaction/#{escape_path(id, name: "id")}"))
      end

      # Resolve Dispute.
      #
      # Resolve a transaction dispute
      #
      # @param id [Integer] The unique identifier of the dispute
      # @param resolution [String] Dispute resolution.
      # @param message [String] Reason for resolving
      # @param refund_amount [Integer] The amount to refund, in the subunit of your integration currency
      # @param uploaded_filename [String] Filename of attachment returned via response from the Dispute upload URL
      # @param evidence [Integer] Evidence Id for fraud claims
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dispute/#resolve
      def resolve(id:, resolution:, message:, refund_amount:, uploaded_filename:, evidence: nil)
        validate_presence!(value: id, name: "id")
        validate_presence!(value: resolution, name: "resolution")
        validate_presence!(value: message, name: "message")
        validate_presence!(value: refund_amount, name: "refund_amount")
        validate_presence!(value: uploaded_filename, name: "uploaded_filename")

        wire_body = to_wire(
          {
            resolution:,
            message:,
            refund_amount:,
            uploaded_filename:,
            evidence:
          },
          WIRE_NAMES
        )

        handle_response(
          @connection.put("/dispute/#{escape_path(id, name: "id")}/resolve", wire_body)
        )
      end

      # Add Evidence.
      #
      # Provide evidence for a dispute
      #
      # @param id [Integer] The unique identifier of the dispute
      # @param customer_email [String] Customer email
      # @param customer_name [String] Customer name
      # @param customer_phone [String] Customer mobile number
      # @param service_details [String] Details of service offered
      # @param delivery_address [String] Delivery address
      # @param delivery_date [String] ISO 8601 representation of delivery date (YYYY-MM-DD)
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/dispute/#evidence
      def add_evidence(
        id:,
        customer_email:,
        customer_name:,
        customer_phone:,
        service_details:,
        delivery_address: nil,
        delivery_date: nil
      )
        validate_presence!(value: id, name: "id")
        validate_presence!(value: customer_email, name: "customer_email")
        validate_presence!(value: customer_name, name: "customer_name")
        validate_presence!(value: customer_phone, name: "customer_phone")
        validate_presence!(value: service_details, name: "service_details")

        wire_body = to_wire(
          {
            customer_email:,
            customer_name:,
            customer_phone:,
            service_details:,
            delivery_address:,
            delivery_date: format_datetime(delivery_date, name: "delivery_date")
          },
          WIRE_NAMES
        )

        handle_response(
          @connection.post("/dispute/#{escape_path(id, name: "id")}/evidence", wire_body)
        )
      end
    end
  end
end
