# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Integration`. Hand-written extras go in lib/paystack_sdk/resources/extensions/integrations.rb.
# scaffold-digest: c66a97cf4f3ad0acac37d43be91b77b75dbe9756c9a950a6ade38570bcff1155

require_relative "base"

module PaystackSdk
  module Resources
    # Integration operations.
    class Integrations < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {}.freeze

      # Fetch Payment Session Timeout.
      #
      # Fetch the session timeout of a transaction
      #
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/integration/#fetch-timeout
      def fetch_payment_session_timeout
        handle_response(@connection.get("/integration/payment_session_timeout"))
      end

      # Update Payment Session Timeout.
      #
      # Update the session timeout of a transaction
      #
      # @param timeout [Integer] Time in seconds before a transaction becomes invalid
      # @note Changes the payment session timeout of the whole integration (account-wide), and the
      #   setting may be shared with LIVE mode even when you call it with a test key (sk_test_). It
      #   has not been verified against the live API. Read the current value with
      #   `fetch_payment_session_timeout` first, and do not call this to try the API out.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/integration/#update-timeout
      def update_payment_session_timeout(timeout:)
        validate_presence!(value: timeout, name: "timeout")

        wire_body = to_wire({timeout:}, WIRE_NAMES)

        handle_response(@connection.put("/integration/payment_session_timeout", wire_body))
      end
    end
  end
end
