# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Miscellaneous`. Hand-written extras go in lib/paystack_sdk/resources/extensions/miscellaneous.rb.
# scaffold-digest: 8e7d4c28f7e3c3f3baf040728f045e40db76fde00fb4b14a38b64ea234035f27

require_relative "base"

module PaystackSdk
  module Resources
    # Miscellaneous operations.
    class Miscellaneous < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {}.freeze

      # Resolve Card BIN.
      #
      # Get the details of a card BIN
      #
      # @param bin [String] The card bank identification number
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/verification/#resolve-card
      def resolve_card_bin(bin:)
        validate_presence!(value: bin, name: "bin")

        handle_response(@connection.get("/decision/bin/#{escape_path(bin, name: "bin")}"))
      end

      # List Countries.
      #
      # List all supported countries on Paystack
      #
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/miscellaneous/#country
      def list_countries
        handle_response(@connection.get("/country"))
      end

      # List States (AVS).
      #
      # Get a list of states for a country for address verification
      #
      # @param country [String] The country code of the states to list.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/miscellaneous/#avs-states
      def list_states(country:)
        validate_presence!(value: country, name: "country")

        wire_query = to_wire({country:}, WIRE_NAMES)

        handle_response(@connection.get("/address_verification/states", wire_query))
      end
    end
  end
end
