# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Order`. Hand-written extras go in lib/paystack_sdk/resources/extensions/orders.rb.
# scaffold-digest: 5f9842687d96069840a503e158175f928f772920f8a52ddf21c682e186ede2fb

require_relative "base"

module PaystackSdk
  module Resources
    # Order operations.
    class Orders < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Orders.
      #
      # List the previously created orders
      #
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The section to retrieve
      # @param from [String] The start date
      # @param to [String] The end date
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/order/#list
      def list(per_page: nil, page: nil, from: nil, to: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire(
          {
            per_page:,
            page:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to")
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/order", wire_query))
      end

      # Create Order.
      #
      # Create an order for selected items
      #
      # @param email [String] The email of the customer placing the order
      # @param first_name [String] The customer's first name
      # @param last_name [String] The customer's last name
      # @param phone [String] The customer's mobile number
      # @param currency [String] Currency in which amount is set One of: GHS, KES, NGN, USD, ZAR.
      # @param items [Array]
      # @param shipping [Hash] The shipping details of the order
      # @param is_gift [Boolean] A flag to indicate if the order is for someone else
      # @param pay_for_me [Boolean] A flag to indicate if the someone else should pay for the order
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/order/#create
      def create(
        email:,
        first_name:,
        last_name:,
        phone:,
        currency:,
        items:,
        shipping:,
        is_gift: nil,
        pay_for_me: nil
      )
        validate_presence!(value: email, name: "email")
        validate_email!(email: email, name: "email")
        validate_presence!(value: first_name, name: "first_name")
        validate_presence!(value: last_name, name: "last_name")
        validate_presence!(value: phone, name: "phone")
        validate_presence!(value: currency, name: "currency")
        validate_allowed_values!(
          value: currency,
          allowed_values: %w[GHS KES NGN USD ZAR],
          name: "currency"
        )
        validate_presence!(value: items, name: "items")
        validate_presence!(value: shipping, name: "shipping")

        wire_body = to_wire(
          {
            email:,
            first_name:,
            last_name:,
            phone:,
            currency:,
            items:,
            shipping:,
            is_gift:,
            pay_for_me:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/order", wire_body))
      end

      # Fetch Order.
      #
      # Fetch the details of a previously created order
      #
      # @param id [Integer] The unique identifier of the order
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/order/#fetch
      def fetch(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/order/#{escape_path(id, name: "id")}"))
      end

      # Fetch Product Orders.
      #
      # Fetch all orders for a particular product
      #
      # @param id [Integer] The unique identifier of the order
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/order/#fetch-product-orders
      def fetch_product_orders(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/order/product/#{escape_path(id, name: "id")}"))
      end

      # Validate Order.
      #
      # Validate a pay for me order
      #
      # @param code [String] The unique code of a previously created order
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/order/#validate
      def validate(code:)
        validate_presence!(value: code, name: "code")

        handle_response(@connection.get("/order/#{escape_path(code, name: "code")}/validate"))
      end
    end
  end
end
