# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Page`. Hand-written extras go in lib/paystack_sdk/resources/extensions/pages.rb.
# scaffold-digest: f15b7bfc076c2ac6bb204df7507b0749dc9129df3b73b6317943835374ffb891

require_relative "base"

module PaystackSdk
  module Resources
    # Page operations.
    class Pages < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Pages.
      #
      # List all previously created payment pages
      #
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The section to retrieve
      # @param from [String] The start date
      # @param to [String] The end date
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/page/#list
      def list(per_page: nil, page: nil, from: nil, to: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire(
          {
            per_page:,
            page:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to")
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/page", wire_query))
      end

      # Create Page.
      #
      # Create a webpage to receive payments
      #
      # @param name [String] Name of page
      # @param description [String] The description of the page
      # @param amount [Integer] Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR
      # @param currency [String] The transaction currency. One of: NGN, GHS, ZAR, KES, USD.
      # @param slug [String] URL slug you would like to be associated with this page.
      # @param type [String] The type of payment page to create. One of: payment, subscription, product, plan.
      # @param plan [String] The ID of the plan to subscribe customers on this payment page to when `type` is set to `subscription`.
      # @param fixed_amount [Boolean] Specifies whether to collect a fixed amount on the payment page.
      # @param split_code [String] The split code of the transaction split.
      # @param metadata [Hash] JSON object of custom data
      # @param redirect_url [String] If you would like Paystack to redirect to a URL upon successful payment, specify the URL here.
      # @param success_message [String] A success message to display to the customer after a successful transaction
      # @param notification_email [String] An email address that will receive transaction notifications for this payment page
      # @param collect_phone [Boolean] Specify whether to collect phone numbers on the payment page
      # @param custom_fields [Array] If you would like to accept custom fields, specify them here.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/page/#create
      def create(
        name:,
        description: nil,
        amount: nil,
        currency: nil,
        slug: nil,
        type: nil,
        plan: nil,
        fixed_amount: nil,
        split_code: nil,
        metadata: nil,
        redirect_url: nil,
        success_message: nil,
        notification_email: nil,
        collect_phone: nil,
        custom_fields: nil
      )
        validate_presence!(value: name, name: "name")
        validate_positive_integer!(value: amount, name: "amount")
        validate_allowed_values!(
          value: currency,
          allowed_values: %w[NGN GHS ZAR KES USD],
          name: "currency"
        )
        validate_allowed_values!(
          value: type,
          allowed_values: %w[payment subscription product plan],
          name: "type"
        )

        wire_body = to_wire(
          {
            name:,
            description:,
            amount:,
            currency:,
            slug:,
            type:,
            plan:,
            fixed_amount:,
            split_code:,
            metadata:,
            redirect_url:,
            success_message:,
            notification_email:,
            collect_phone:,
            custom_fields:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/page", wire_body))
      end

      # Fetch Page.
      #
      # Get a previously created payment page
      #
      # @param id_or_slug [String] The unique identifier of a payment page
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/page/#fetch
      def fetch(id_or_slug:)
        validate_presence!(value: id_or_slug, name: "id_or_slug")

        handle_response(@connection.get("/page/#{escape_path(id_or_slug, name: "id_or_slug")}"))
      end

      # Update Page.
      #
      # Update a previously created payment page
      #
      # @param id_or_slug [String] The unique identifier of a payment page
      # @param name [String] Name of page
      # @param description [String] The description of the page
      # @param amount [Integer] Amount should be in the subunit of the currency
      # @param active [Boolean] Set to false to deactivate page url
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/page/#update
      def update(id_or_slug:, name: nil, description: nil, amount: nil, active: nil)
        validate_presence!(value: id_or_slug, name: "id_or_slug")
        validate_positive_integer!(value: amount, name: "amount")

        wire_body = to_wire({name:, description:, amount:, active:}, WIRE_NAMES)

        handle_response(
          @connection.put("/page/#{escape_path(id_or_slug, name: "id_or_slug")}", wire_body)
        )
      end

      # Check Slug Availability.
      #
      # Check if a custom slug is available for use when creating a payment page
      #
      # @param slug [String] The custom slug to check
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/page/#check-slug
      def check_slug_availability(slug:)
        validate_presence!(value: slug, name: "slug")

        handle_response(
          @connection.get("/page/check_slug_availability/#{escape_path(slug, name: "slug")}")
        )
      end

      # Add Products.
      #
      # Add products to a previously created payment page.
      #
      # @param id [Integer]
      # @param products [Array] A list of IDs of products to add to a page.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/page/#add-products
      def add_products(id:, products:)
        validate_presence!(value: id, name: "id")
        validate_presence!(value: products, name: "products")

        wire_body = to_wire({products:}, WIRE_NAMES)

        handle_response(@connection.post("/page/#{escape_path(id, name: "id")}/product", wire_body))
      end
    end
  end
end
