# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Payment Request`. Hand-written extras go in lib/paystack_sdk/resources/extensions/payment_requests.rb.
# scaffold-digest: 884176d0fce2f23befd4655d04efd15b5dccf6808f496f41b09e0afcd43c1e73

require_relative "base"

module PaystackSdk
  module Resources
    # Payment Request operations.
    class PaymentRequests < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage", customer_id: "customer"}.freeze

      # List Payment Request.
      #
      # List all previously created payment requests to your customers
      #
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The section to retrieve
      # @param customer_id [Integer] Customer ID
      # @param status [String] Invoice status to filter One of: draft, pending, success, failed.
      # @param currency [String] If your integration supports more than one currency, choose the one to filter
      # @param from [String] The start date
      # @param to [String] The end date
      # @param include_archive [Boolean] Pass true to include archived payment requests.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/payment-request/#list
      def list(
        per_page: nil,
        page: nil,
        customer_id: nil,
        status: nil,
        currency: nil,
        from: nil,
        to: nil,
        include_archive: nil
      )
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")
        validate_allowed_values!(
          value: status,
          allowed_values: %w[draft pending success failed],
          name: "status"
        )

        wire_query = to_wire(
          {
            per_page:,
            page:,
            customer_id:,
            status:,
            currency:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to"),
            include_archive:
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/paymentrequest", wire_query))
      end

      # Create Payment Request.
      #
      # Create a new payment request by issuing an invoice to a customer
      #
      # @param customer [String] Customer id or code
      # @param amount [Integer] The amount in the subunit.
      # @param currency [String] Specify the currency of the invoice.
      # @param due_date [String] ISO 8601 date or date-time the request is due, for example 2026-12-31 or 2026-12-31T23:00:00Z.
      # @param description [String] A short description of the payment request
      # @param line_items [Array] Line items, each a Hash such as {name: "item 1", amount: 2000, quantity: 1} (amount in the subunit).
      # @param tax [Array] Taxes, each a Hash such as {name: "VAT", amount: 2000} (amount in the subunit).
      # @param send_notification [Boolean] Indicates whether Paystack sends an email notification to customer.
      # @param draft [Boolean] Indicate if request should be saved as draft.
      # @param has_invoice [Boolean] Set to true to create a draft invoice (adds an auto incrementing invoice number if none is provided) even if there are no line_items or tax passed
      # @param invoice_number [Integer] Numeric value of invoice.
      # @param split_code [String] The split code of the transaction split.
      # @param metadata [Hash] A Hash of custom data, stored on the payment request.
      # @param redirect_url [String] A URL for Paystack to redirect to after a successful payment.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/payment-request/#create
      def create(
        customer:,
        amount: nil,
        currency: nil,
        due_date: nil,
        description: nil,
        line_items: nil,
        tax: nil,
        send_notification: nil,
        draft: nil,
        has_invoice: nil,
        invoice_number: nil,
        split_code: nil,
        metadata: nil,
        redirect_url: nil
      )
        validate_presence!(value: customer, name: "customer")
        validate_positive_integer!(value: amount, name: "amount")

        wire_body = to_wire(
          {
            customer:,
            amount:,
            currency:,
            due_date: format_datetime(due_date, name: "due_date"),
            description:,
            line_items:,
            tax:,
            send_notification:,
            draft:,
            has_invoice:,
            invoice_number:,
            split_code:,
            metadata:,
            redirect_url:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/paymentrequest", wire_body))
      end

      # Fetch Payment Request.
      #
      # Fetch a previously created payment request
      #
      # @param id_or_code [String] The unique identifier of a previously created payment request
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/payment-request/#fetch
      def fetch(id_or_code:)
        validate_presence!(value: id_or_code, name: "id_or_code")

        handle_response(
          @connection.get("/paymentrequest/#{escape_path(id_or_code, name: "id_or_code")}")
        )
      end

      # Update Payment Request.
      #
      # Update a previously created payment request
      #
      # @param id_or_code [String] The unique identifier of a previously created payment request
      # @param customer [String] Customer id or code
      # @param amount [Integer] Payment request amount.
      # @param currency [String] Specify the currency of the invoice.
      # @param due_date [String] ISO 8601 date or date-time the request is due, for example 2026-12-31 or 2026-12-31T23:00:00Z.
      # @param description [String] A short description of the payment request
      # @param line_items [Array] Line items, each a Hash such as {name: "item 1", amount: 2000, quantity: 1} (amount in the subunit).
      # @param tax [Array] Taxes, each a Hash such as {name: "VAT", amount: 2000} (amount in the subunit).
      # @param send_notification [Boolean] Indicates whether Paystack sends an email notification to customer.
      # @param draft [Boolean] Indicate if request should be saved as draft.
      # @param has_invoice [Boolean] Set to true to create a draft invoice (adds an auto incrementing invoice number if none is provided) even if there are no line_items or tax passed
      # @param invoice_number [Integer] Numeric value of invoice.
      # @param split_code [String] The split code of the transaction split.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/payment-request/#update
      def update(
        id_or_code:,
        customer: nil,
        amount: nil,
        currency: nil,
        due_date: nil,
        description: nil,
        line_items: nil,
        tax: nil,
        send_notification: nil,
        draft: nil,
        has_invoice: nil,
        invoice_number: nil,
        split_code: nil
      )
        validate_presence!(value: id_or_code, name: "id_or_code")
        validate_positive_integer!(value: amount, name: "amount")

        wire_body = to_wire(
          {
            customer:,
            amount:,
            currency:,
            due_date: format_datetime(due_date, name: "due_date"),
            description:,
            line_items:,
            tax:,
            send_notification:,
            draft:,
            has_invoice:,
            invoice_number:,
            split_code:
          },
          WIRE_NAMES
        )

        handle_response(
          @connection.put("/paymentrequest/#{escape_path(id_or_code, name: "id_or_code")}", wire_body)
        )
      end

      # Verify Payment Request.
      #
      # Verify the status of a previously created payment request
      #
      # @param code [String] The unique identifier of a previously created payment request
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/payment-request/#verify
      def verify(code:)
        validate_presence!(value: code, name: "code")

        handle_response(
          @connection.get("/paymentrequest/verify/#{escape_path(code, name: "code")}")
        )
      end

      # Send Notification.
      #
      # Trigger an email reminder to a customer for a previously created payment request
      #
      # @param code [String] The unique identifier of a previously created payment request
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/payment-request/#send-notification
      def notify(code:)
        validate_presence!(value: code, name: "code")

        handle_response(
          @connection.post("/paymentrequest/notify/#{escape_path(code, name: "code")}")
        )
      end

      # Payment Request Total.
      #
      # Get the metric of all pending and successful payment requests
      #
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/payment-request/#total
      def totals
        handle_response(@connection.get("/paymentrequest/totals"))
      end

      # Finalize Payment Request.
      #
      # Finalise the creation of a draft payment request for a customer
      #
      # @param id_or_code [String] The unique identifier of a draft payment request
      # @param send_notification [Boolean] Whether Paystack emails the customer; defaults to true.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/payment-request/#finalize
      def finalize(id_or_code:, send_notification: nil)
        validate_presence!(value: id_or_code, name: "id_or_code")

        wire_body = to_wire({send_notification:}, WIRE_NAMES)

        handle_response(
          @connection.post("/paymentrequest/finalize/#{escape_path(id_or_code, name: "id_or_code")}", wire_body)
        )
      end

      # Archive Payment Request.
      #
      # Archive a payment request to clean up your records.
      #
      # @param id_or_code [String] The unique identifier of a previously created payment request
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/payment-request/#archive
      def archive(id_or_code:)
        validate_presence!(value: id_or_code, name: "id_or_code")

        handle_response(
          @connection.post("/paymentrequest/archive/#{escape_path(id_or_code, name: "id_or_code")}")
        )
      end
    end
  end
end
