# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Plan`. Hand-written extras go in lib/paystack_sdk/resources/extensions/plans.rb.
# scaffold-digest: 68769f801c1b9e113bc52707375e9ffd37cf248629d9454a18c3d690571e9996

require_relative "base"

module PaystackSdk
  module Resources
    # Plan operations.
    class Plans < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Plans.
      #
      # List all recurring payment plans
      #
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The section to retrieve
      # @param interval [String] Specify interval of the plan One of: hourly, daily, weekly, monthly, quarterly, biannually, annually.
      # @param amount [Integer] The amount on the plans to retrieve
      # @param from [String] The start date
      # @param to [String] The end date
      # @param status [String] Filter list by plans with specified status.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/plan/#list
      def list(
        per_page: nil,
        page: nil,
        interval: nil,
        amount: nil,
        from: nil,
        to: nil,
        status: nil
      )
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")
        validate_allowed_values!(
          value: interval,
          allowed_values: %w[hourly daily weekly monthly quarterly biannually annually],
          name: "interval"
        )
        validate_positive_integer!(value: amount, name: "amount")

        wire_query = to_wire(
          {
            per_page:,
            page:,
            interval:,
            amount:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to"),
            status:
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/plan", wire_query))
      end

      # Create Plan.
      #
      # Create a plan for recurring payments
      #
      # @param name [String] Name of plan
      # @param amount [Integer] Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR
      # @param interval [String] Payment interval One of: hourly, daily, weekly, monthly, quarterly, biannually, annually.
      # @param description [String] A description for this plan
      # @param send_invoices [Boolean] Set to false if you don't want invoices to be sent to your customers
      # @param send_sms [Boolean] Set to false if you don't want text messages to be sent to your customers
      # @param currency [String] Currency in which amount is set.
      # @param invoice_limit [Integer] Number of invoices to raise during subscription to this plan.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/plan/#create
      def create(
        name:,
        amount:,
        interval:,
        description: nil,
        send_invoices: nil,
        send_sms: nil,
        currency: nil,
        invoice_limit: nil
      )
        validate_presence!(value: name, name: "name")
        validate_presence!(value: amount, name: "amount")
        validate_positive_integer!(value: amount, name: "amount")
        validate_presence!(value: interval, name: "interval")
        validate_allowed_values!(
          value: interval,
          allowed_values: %w[hourly daily weekly monthly quarterly biannually annually],
          name: "interval"
        )

        wire_body = to_wire(
          {
            name:,
            amount:,
            interval:,
            description:,
            send_invoices:,
            send_sms:,
            currency:,
            invoice_limit:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/plan", wire_body))
      end

      # Fetch Plan.
      #
      # Get the details of a payment plan
      #
      # @param id_or_code [String] The plan code you want to fetch
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/plan/#fetch
      def fetch(id_or_code:)
        validate_presence!(value: id_or_code, name: "id_or_code")

        handle_response(@connection.get("/plan/#{escape_path(id_or_code, name: "id_or_code")}"))
      end

      # Update Plan.
      #
      # Update a plan details on your integration
      #
      # @param id_or_code [String] The plan code you want to fetch
      # @param name [String] Name of plan
      # @param amount [Integer] Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR
      # @param interval [String] Payment interval One of: hourly, daily, weekly, monthly, quarterly, biannually, annually.
      # @param description [String] A description for this plan
      # @param send_invoices [Boolean] Set to false if you don't want invoices to be sent to your customers
      # @param send_sms [Boolean] Set to false if you don't want text messages to be sent to your customers
      # @param currency [String] Currency in which amount is set.
      # @param invoice_limit [Integer] Number of invoices to raise during subscription to this plan.
      # @param update_existing_subscriptions [Boolean] Set to true if you want the existing subscriptions to use the new changes.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/plan/#update
      def update(
        id_or_code:,
        name: nil,
        amount: nil,
        interval: nil,
        description: nil,
        send_invoices: nil,
        send_sms: nil,
        currency: nil,
        invoice_limit: nil,
        update_existing_subscriptions: nil
      )
        validate_presence!(value: id_or_code, name: "id_or_code")
        validate_positive_integer!(value: amount, name: "amount")
        validate_allowed_values!(
          value: interval,
          allowed_values: %w[hourly daily weekly monthly quarterly biannually annually],
          name: "interval"
        )

        wire_body = to_wire(
          {
            name:,
            amount:,
            interval:,
            description:,
            send_invoices:,
            send_sms:,
            currency:,
            invoice_limit:,
            update_existing_subscriptions:
          },
          WIRE_NAMES
        )

        handle_response(
          @connection.put("/plan/#{escape_path(id_or_code, name: "id_or_code")}", wire_body)
        )
      end
    end
  end
end
