# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Product`. Hand-written extras go in lib/paystack_sdk/resources/extensions/products.rb.
# scaffold-digest: 40ad36eb6641d3f3dc5f272c7c372ae279002d7bb64a3ac51b2ae5d8b4af3c5e

require_relative "base"

module PaystackSdk
  module Resources
    # Product operations.
    class Products < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Products.
      #
      # List all previously created products
      #
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The section to retrieve
      # @param active [Boolean] The state of the product
      # @param from [String] The start date
      # @param to [String] The end date
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/product/#list
      def list(per_page: nil, page: nil, active: nil, from: nil, to: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire(
          {
            per_page:,
            page:,
            active:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to")
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/product", wire_query))
      end

      # Create Product.
      #
      # Create a new product on your integration
      #
      # @param name [String] Name of product
      # @param price [Integer] Price should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR
      # @param currency [String] Currency in which price is set.
      # @param description [String] The description of the product.
      # @param unlimited [Boolean] Set to true if the product has unlimited stock.
      # @param quantity [Integer] Number of products in stock.
      # @param split_code [String] The split code if sharing the transaction with partners
      # @param metadata [Hash] A set of key/value pairs that you can attach to the product.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/product/#create
      def create(
        name:,
        price:,
        currency:,
        description: nil,
        unlimited: nil,
        quantity: nil,
        split_code: nil,
        metadata: nil
      )
        validate_presence!(value: name, name: "name")
        validate_presence!(value: price, name: "price")
        validate_presence!(value: currency, name: "currency")

        wire_body = to_wire(
          {
            name:,
            price:,
            currency:,
            description:,
            unlimited:,
            quantity:,
            split_code:,
            metadata:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/product", wire_body))
      end

      # Fetch Product.
      #
      # Fetch a previously created product
      #
      # @param id [Integer] The unique identifier of the product
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/product/#fetch
      def fetch(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/product/#{escape_path(id, name: "id")}"))
      end

      # Update product.
      #
      # Update a previously created product
      #
      # @param id [Integer] The unique identifier of the product
      # @param name [String] Name of product
      # @param description [String] The description of the product
      # @param price [Integer] Price should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR
      # @param currency [String] Currency in which price is set.
      # @param unlimited [Boolean] Set to true if the product has unlimited stock.
      # @param quantity [Integer] Number of products in stock.
      # @param split_code [String] The split code if sharing the transaction with partners
      # @param metadata [Hash] JSON object of custom data
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/product/#update
      def update(
        id:,
        name: nil,
        description: nil,
        price: nil,
        currency: nil,
        unlimited: nil,
        quantity: nil,
        split_code: nil,
        metadata: nil
      )
        validate_presence!(value: id, name: "id")

        wire_body = to_wire(
          {
            name:,
            description:,
            price:,
            currency:,
            unlimited:,
            quantity:,
            split_code:,
            metadata:
          },
          WIRE_NAMES
        )

        handle_response(@connection.put("/product/#{escape_path(id, name: "id")}", wire_body))
      end

      # Delete Product.
      #
      # Delete a previously created product
      #
      # @param id [Integer] The unique identifier of the product
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/product/#delete-product
      def delete(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.delete("/product/#{escape_path(id, name: "id")}"))
      end
    end
  end
end
