# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Settlement`. Hand-written extras go in lib/paystack_sdk/resources/extensions/settlements.rb.
# scaffold-digest: 026436fb32768e6f2bdba729240aead9977fafe0b99448bb269f1b4429634d78

require_relative "base"

module PaystackSdk
  module Resources
    # Settlement operations.
    class Settlements < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Settlements.
      #
      # List settlements made to your settlement accounts
      #
      # @param per_page [Integer] The number of records to fetch per request
      # @param page [Integer] The offset to retrieve data from
      # @param from [String] A timestamp from which to start listing settlements, for example 2016-09-24T00:00:05.000Z or 2016-09-21.
      # @param to [String] A timestamp at which to stop listing settlements, for example 2016-09-24T00:00:05.000Z or 2016-09-21.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/settlement/#list
      def list(per_page: nil, page: nil, from: nil, to: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire({per_page:, page:, from:, to:}, WIRE_NAMES)

        handle_response(@connection.get("/settlement", wire_query))
      end

      # Fetch Settlement Transactions.
      #
      # Get the transactions that make up a particular settlement
      #
      # @param id [Integer] The settlement ID in which you want to fetch its transactions
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/settlement/#transactions
      def transactions(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/settlement/#{escape_path(id, name: "id")}/transactions"))
      end
    end
  end
end
