# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Split`. Hand-written extras go in lib/paystack_sdk/resources/extensions/splits.rb.
# scaffold-digest: 7edb268cf2271c4fb1af0cf5284840af3e3adbafe31ea1cbc2acfd4dc2c88d10

require_relative "base"

module PaystackSdk
  module Resources
    # Split operations.
    class Splits < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Splits.
      #
      # List the transaction splits available on your integration
      #
      # @param subaccount_code [String] Filter by subaccount code
      # @param name [String] The name of the split
      # @param active [Boolean] The status of the split
      # @param per_page [Integer] The number of records to fetch per request
      # @param page [Integer] The offset to retrieve data from
      # @param from [String] The start date
      # @param to [String] The end date
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/split/#list
      def list(
        subaccount_code: nil,
        name: nil,
        active: nil,
        per_page: nil,
        page: nil,
        from: nil,
        to: nil
      )
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire(
          {
            subaccount_code:,
            name:,
            active:,
            per_page:,
            page:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to")
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/split", wire_query))
      end

      # Create Split.
      #
      # Create a split configuration for transactions
      #
      # @param name [String] Name of the transaction split
      # @param type [String] The type of transaction split you want to create. One of: percentage, flat.
      # @param subaccounts [Array] A list of object containing subaccount code and number of shares
      # @param currency [String] The transaction currency One of: NGN, GHS, ZAR, USD.
      # @param bearer_type [String] This allows you specify how the transaction charge should be processed One of: subaccount, account, all-proportional, all.
      # @param bearer_subaccount [String] This is the subaccount code of the customer or partner that would bear the transaction charge if you specified subaccount as the bearer type
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/split/#create
      def create(name:, type:, subaccounts:, currency:, bearer_type: nil, bearer_subaccount: nil)
        validate_presence!(value: name, name: "name")
        validate_presence!(value: type, name: "type")
        validate_allowed_values!(value: type, allowed_values: %w[percentage flat], name: "type")
        validate_presence!(value: subaccounts, name: "subaccounts")
        validate_presence!(value: currency, name: "currency")
        validate_allowed_values!(
          value: currency,
          allowed_values: %w[NGN GHS ZAR USD],
          name: "currency"
        )
        validate_allowed_values!(
          value: bearer_type,
          allowed_values: %w[subaccount account all-proportional all],
          name: "bearer_type"
        )

        wire_body = to_wire(
          {
            name:,
            type:,
            subaccounts:,
            currency:,
            bearer_type:,
            bearer_subaccount:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/split", wire_body))
      end

      # Fetch Split.
      #
      # Get details of a split configuration for a transaction
      #
      # @param id [String] The ID of the split configuration to fetch
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/split/#fetch
      def fetch(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/split/#{escape_path(id, name: "id")}"))
      end

      # Update Split.
      #
      # Update a split configuration for transactions
      #
      # @param id [String]
      # @param name [String] Name of the transaction split
      # @param active [Boolean] Toggle status of split.
      # @param bearer_type [String] This allows you specify how the transaction charge should be processed One of: subaccount, account, all-proportional, all.
      # @param bearer_subaccount [String] This is the subaccount code of the customer or partner that would bear the transaction charge if you specified subaccount as the bearer type
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/split/#update
      def update(id:, name: nil, active: nil, bearer_type: nil, bearer_subaccount: nil)
        validate_presence!(value: id, name: "id")
        validate_allowed_values!(
          value: bearer_type,
          allowed_values: %w[subaccount account all-proportional all],
          name: "bearer_type"
        )

        wire_body = to_wire({name:, active:, bearer_type:, bearer_subaccount:}, WIRE_NAMES)

        handle_response(@connection.put("/split/#{escape_path(id, name: "id")}", wire_body))
      end

      # Add Subaccount to Split.
      #
      # Add a subaccount to a split configuration, or update the share of an existing subaccount
      #
      # @param id [Integer] The ID of the split configuration to fetch
      # @param subaccount [String] Subaccount code of the customer or partner
      # @param share [Integer] The percentage or flat quota of the customer or partner
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/split/#add-subaccount
      def add_subaccount(id:, subaccount:, share:)
        validate_presence!(value: id, name: "id")
        validate_presence!(value: subaccount, name: "subaccount")
        validate_presence!(value: share, name: "share")

        wire_body = to_wire({subaccount:, share:}, WIRE_NAMES)

        handle_response(
          @connection.post("/split/#{escape_path(id, name: "id")}/subaccount/add", wire_body)
        )
      end

      # Remove Subaccount from split.
      #
      # Remove a subaccount from a split configuration
      #
      # @param id [Integer] The ID of the split configuration to fetch
      # @param subaccount [String] Subaccount code of the customer or partner
      # @param share [Integer] Not used when removing a subaccount; the docs do not list it, and Paystack removes the subaccount whatever share is sent.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/split/#remove-subaccount
      def remove_subaccount(id:, subaccount:, share: nil)
        validate_presence!(value: id, name: "id")
        validate_presence!(value: subaccount, name: "subaccount")

        wire_body = to_wire({subaccount:, share:}, WIRE_NAMES)

        handle_response(
          @connection.post("/split/#{escape_path(id, name: "id")}/subaccount/remove", wire_body)
        )
      end
    end
  end
end
