# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Storefront`. Hand-written extras go in lib/paystack_sdk/resources/extensions/storefronts.rb.
# scaffold-digest: c569580b4ac53036d82e0b7d2d9dd17323e11da35951df7ba4d192c5fdf48cb1

require_relative "base"

module PaystackSdk
  module Resources
    # Storefront operations.
    class Storefronts < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Storefronts.
      #
      # List the storefronts you previously created
      #
      # @param per_page [Integer] Number of records to fetch per request
      # @param page [Integer] The offset to retrieve data from
      # @param status [String] One of: active, inactive.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#list
      def list(per_page: nil, page: nil, status: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")
        validate_allowed_values!(value: status, allowed_values: %w[active inactive], name: "status")

        wire_query = to_wire({per_page:, page:, status:}, WIRE_NAMES)

        handle_response(@connection.get("/storefront", wire_query))
      end

      # Create Storefront.
      #
      # Create a digital shop to manage and display your products
      #
      # @param name [String] Name of the storefront
      # @param slug [String] A unique identifier to access your store.
      # @param currency [String] Currency for prices of products in your storefront. One of: GHS, KES, NGN, USD, ZAR.
      # @param description [String] The description of the storefront
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#create
      def create(name:, slug:, currency:, description: nil)
        validate_presence!(value: name, name: "name")
        validate_presence!(value: slug, name: "slug")
        validate_presence!(value: currency, name: "currency")
        validate_allowed_values!(
          value: currency,
          allowed_values: %w[GHS KES NGN USD ZAR],
          name: "currency"
        )

        wire_body = to_wire({name:, slug:, currency:, description:}, WIRE_NAMES)

        handle_response(@connection.post("/storefront", wire_body))
      end

      # Fetch Storefront.
      #
      # Get the details of a previously created Storefront
      #
      # @param id [Integer] The unique identifier of the Storefront
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#fetch
      def fetch(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/storefront/#{escape_path(id, name: "id")}"))
      end

      # Update Storefront.
      #
      # Update the details of a previously created Storefront
      #
      # @param id [Integer] The unique identifier of the Storefront
      # @param name [String] Name of the storefront
      # @param slug [String] A unique identifier to access your store.
      # @param description [String] The description of the storefront
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#update
      def update(id:, name: nil, slug: nil, description: nil)
        validate_presence!(value: id, name: "id")

        wire_body = to_wire({name:, slug:, description:}, WIRE_NAMES)

        handle_response(@connection.put("/storefront/#{escape_path(id, name: "id")}", wire_body))
      end

      # Delete Storefront.
      #
      # Delete a previously created Storefront
      #
      # @param id [Integer] The unique identifier of the Storefront
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#delete
      def delete(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.delete("/storefront/#{escape_path(id, name: "id")}"))
      end

      # Verify Storefront Slug.
      #
      # Verify the availability of a slug before using it for your Storefront
      #
      # @param slug [String] The custom slug to check
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#verify-slug
      def verify_slug(slug:)
        validate_presence!(value: slug, name: "slug")

        handle_response(@connection.get("/storefront/verify/#{escape_path(slug, name: "slug")}"))
      end

      # Fetch Storefront Orders.
      #
      # Fetch all orders in your Storefront
      #
      # @param id [Integer] The unique identifier of the Storefront
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#fetch-orders
      def fetch_orders(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/storefront/#{escape_path(id, name: "id")}/order"))
      end

      # List Storefront Products.
      #
      # List the products in a Storefront
      #
      # @param id [Integer] The unique identifier of the Storefront
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#list-products
      def list_products(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/storefront/#{escape_path(id, name: "id")}/product"))
      end

      # Add Products to Storefront.
      #
      # Add previously created products to a Storefront
      #
      # @param id [Integer] The unique identifier of the Storefront
      # @param products [Array] An array of product IDs
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#add-products
      def add_products(id:, products:)
        validate_presence!(value: id, name: "id")
        validate_presence!(value: products, name: "products")

        wire_body = to_wire({products:}, WIRE_NAMES)

        handle_response(
          @connection.post("/storefront/#{escape_path(id, name: "id")}/product", wire_body)
        )
      end

      # Publish Storefront.
      #
      # Make your Storefront publicly available
      #
      # @param id [Integer] The unique identifier of the Storefront
      # @note Publishing copies the storefront and its products into LIVE mode, even when you call
      #   it with a test key (sk_test_). The live copy is active, can be found by its slug, and
      #   cannot be read or deleted with a test key. Do not call this to try the API out; use
      #   `duplicate` instead.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#publish
      def publish(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.post("/storefront/#{escape_path(id, name: "id")}/publish"))
      end

      # Duplicate Storefront.
      #
      # Duplicate a previously created Storefront
      #
      # @param id [Integer] The unique identifier of the Storefront
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/storefront/#duplicate
      def duplicate(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.post("/storefront/#{escape_path(id, name: "id")}/duplicate"))
      end
    end
  end
end
