# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Subaccount`. Hand-written extras go in lib/paystack_sdk/resources/extensions/subaccounts.rb.
# scaffold-digest: 12bf5e22e401e42aaaa904492375cd7907a5def71857ca70a6dce849e73aa590

require_relative "base"

module PaystackSdk
  module Resources
    # Subaccount operations.
    class Subaccounts < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Subaccounts.
      #
      # List subaccounts available on your integration
      #
      # @param per_page [Integer] Number of records to fetch per request
      # @param page [Integer] The offset to retrieve data from
      # @param active [Integer] Filter by the state of the subaccounts
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subaccount/#list-subaccounts
      def list(per_page: nil, page: nil, active: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire({per_page:, page:, active:}, WIRE_NAMES)

        handle_response(@connection.get("/subaccount", wire_query))
      end

      # Create Subaccount.
      #
      # Create a subacount for a partner
      #
      # @param business_name [String] Name of business for subaccount
      # @param bank_code [String] Bank code for the bank, from the List Banks endpoint.
      # @param account_number [String] Bank account number
      # @param percentage_charge [Numeric] The percentage the main account receives from each payment made to the subaccount.
      # @param description [String] A description for this subaccount
      # @param primary_contact_email [String] A contact email for the subaccount
      # @param primary_contact_name [String] The name of the contact person for this subaccount
      # @param primary_contact_phone [String] A phone number to call for this subaccount
      # @param metadata [String] Stringified JSON object of custom data
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subaccount/#create-subaccount
      def create(
        business_name:,
        bank_code:,
        account_number:,
        percentage_charge:,
        description: nil,
        primary_contact_email: nil,
        primary_contact_name: nil,
        primary_contact_phone: nil,
        metadata: nil
      )
        validate_presence!(value: business_name, name: "business_name")
        validate_presence!(value: bank_code, name: "bank_code")
        validate_presence!(value: account_number, name: "account_number")
        validate_presence!(value: percentage_charge, name: "percentage_charge")

        wire_body = to_wire(
          {
            business_name:,
            bank_code:,
            account_number:,
            percentage_charge:,
            description:,
            primary_contact_email:,
            primary_contact_name:,
            primary_contact_phone:,
            metadata: stringify_json(metadata)
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/subaccount", wire_body))
      end

      # Fetch Subaccount.
      #
      # Get details of a subaccount on your integration
      #
      # @param id_or_code [String] The subaccount code you want to fetch
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subaccount/#fetch-subaccount
      def fetch(id_or_code:)
        validate_presence!(value: id_or_code, name: "id_or_code")

        handle_response(
          @connection.get("/subaccount/#{escape_path(id_or_code, name: "id_or_code")}")
        )
      end

      # Update Subaccount.
      #
      # Update a subaccount details on your integration
      #
      # @param id_or_code [String] The subaccount code you want to fetch
      # @param business_name [String] Name of business for subaccount
      # @param bank_code [String] Bank code for the bank, from the List Banks endpoint.
      # @param account_number [String] Bank account number
      # @param active [Boolean] Activate or deactivate a subaccount
      # @param percentage_charge [Numeric] The default percentage charged when receiving on behalf of this subaccount.
      # @param description [String] A description for this subaccount
      # @param primary_contact_email [String] A contact email for the subaccount
      # @param primary_contact_name [String] The name of the contact person for this subaccount
      # @param primary_contact_phone [String] A phone number to call for this subaccount
      # @param metadata [String] Stringified JSON object of custom data
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subaccount/#update-subaccount
      def update(
        id_or_code:,
        business_name: nil,
        bank_code: nil,
        account_number: nil,
        active: nil,
        percentage_charge: nil,
        description: nil,
        primary_contact_email: nil,
        primary_contact_name: nil,
        primary_contact_phone: nil,
        metadata: nil
      )
        validate_presence!(value: id_or_code, name: "id_or_code")

        wire_body = to_wire(
          {
            business_name:,
            bank_code:,
            account_number:,
            active:,
            percentage_charge:,
            description:,
            primary_contact_email:,
            primary_contact_name:,
            primary_contact_phone:,
            metadata: stringify_json(metadata)
          },
          WIRE_NAMES
        )

        handle_response(
          @connection.put("/subaccount/#{escape_path(id_or_code, name: "id_or_code")}", wire_body)
        )
      end
    end
  end
end
