# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Subscription`. Hand-written extras go in lib/paystack_sdk/resources/extensions/subscriptions.rb.
# scaffold-digest: bf9e49fa6de4d23b295572c9c4fc3aa74477986410dd3f858145f2e4239d0444

require_relative "base"

module PaystackSdk
  module Resources
    # Subscription operations.
    class Subscriptions < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage", plan_id: "plan", customer_id: "customer"}.freeze

      # List Subscriptions.
      #
      # List all subscriptions available on your integration
      #
      # @param per_page [Integer] Number of records to fetch per page
      # @param page [Integer] The section to retrieve
      # @param plan_id [Integer] Plan ID
      # @param customer_id [Integer] Customer ID
      # @param from [String] The start date
      # @param to [String] The end date
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subscription/#list
      def list(per_page: nil, page: nil, plan_id: nil, customer_id: nil, from: nil, to: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire(
          {
            per_page:,
            page:,
            plan_id:,
            customer_id:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to")
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/subscription", wire_query))
      end

      # Create Subscription.
      #
      # Create a subscription a customer
      #
      # @param customer [String] Customer's email address or customer code
      # @param plan [String] Plan code
      # @param authorization [String] If customer has multiple authorizations, you can set the desired authorization you wish to use for this subscription here.
      # @param start_date [String] Set the date for the first debit.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subscription/#create
      def create(customer:, plan:, authorization: nil, start_date: nil)
        validate_presence!(value: customer, name: "customer")
        validate_presence!(value: plan, name: "plan")

        wire_body = to_wire(
          {
            customer:,
            plan:,
            authorization:,
            start_date: format_datetime(start_date, name: "start_date")
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/subscription", wire_body))
      end

      # Fetch Subscription.
      #
      # Get details of a customer's subscription
      #
      # @param id_or_code [String] The subscription code for the subscription you want to fetch
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subscription/#fetch
      def fetch(id_or_code:)
        validate_presence!(value: id_or_code, name: "id_or_code")

        handle_response(
          @connection.get("/subscription/#{escape_path(id_or_code, name: "id_or_code")}")
        )
      end

      # Disable Subscription.
      #
      # Disable a subscription on your integration
      #
      # @param code [String] Subscription code
      # @param token [String] Email token
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subscription/#disable
      def disable(code:, token:)
        validate_presence!(value: code, name: "code")
        validate_presence!(value: token, name: "token")

        wire_body = to_wire({code:, token:}, WIRE_NAMES)

        handle_response(@connection.post("/subscription/disable", wire_body))
      end

      # Enable Subscription.
      #
      # Enable a subscription on your integration
      #
      # @param code [String] Subscription code
      # @param token [String] Email token
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subscription/#enable
      def enable(code:, token:)
        validate_presence!(value: code, name: "code")
        validate_presence!(value: token, name: "token")

        wire_body = to_wire({code:, token:}, WIRE_NAMES)

        handle_response(@connection.post("/subscription/enable", wire_body))
      end

      # Generate Update Subscription Link.
      #
      # Generate a link for updating the card on a subscription
      #
      # @param code [String] Subscription code
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subscription/#manage-link
      def generate_update_link(code:)
        validate_presence!(value: code, name: "code")

        handle_response(
          @connection.get("/subscription/#{escape_path(code, name: "code")}/manage/link")
        )
      end

      # Send Update Subscription Link.
      #
      # Email a customer a link for updating the card on their subscription
      #
      # @param code [String] Subscription code
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/subscription/#manage-email
      def send_update_link(code:)
        validate_presence!(value: code, name: "code")

        handle_response(
          @connection.post("/subscription/#{escape_path(code, name: "code")}/manage/email")
        )
      end
    end
  end
end
