# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Terminal`. Hand-written extras go in lib/paystack_sdk/resources/extensions/terminals.rb.
# scaffold-digest: 0b01c27e31f3e144d9463553ec97a1eee95f91d173c35ca5b7cb500cd3872127

require_relative "base"

module PaystackSdk
  module Resources
    # Terminal operations.
    class Terminals < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {next_cursor: "next"}.freeze

      # Send Event.
      #
      # Send an event from your application to the Paystack Terminal
      #
      # @param terminal_id [String] The ID of the Terminal the event should be sent to.
      # @param type [String] The type of event to push One of: invoice, transaction.
      # @param action [String] The action the Terminal needs to perform. One of: process, view, print.
      # @param data [Hash] The parameters needed to perform the specified action
      # @note This pushes the event to a physical Paystack Terminal. Not verified against the
      #   Paystack API: the test account used to build this SDK has no Terminal access.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/terminal/#send-event
      def send_event(terminal_id:, type: nil, action: nil, data: nil)
        validate_presence!(value: terminal_id, name: "terminal_id")
        validate_allowed_values!(value: type, allowed_values: %w[invoice transaction], name: "type")
        validate_allowed_values!(
          value: action,
          allowed_values: %w[process view print],
          name: "action"
        )

        wire_body = to_wire({type:, action:, data:}, WIRE_NAMES)

        handle_response(
          @connection.post("/terminal/#{escape_path(terminal_id, name: "terminal_id")}/event", wire_body)
        )
      end

      # Fetch Event Status.
      #
      # Check the status of an event sent to the Terminal
      #
      # @param terminal_id [String] The ID of the Terminal the event should be sent to.
      # @param event_id [String] The ID of the event that was sent to the Terminal
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/terminal/#fetch-event-status
      def fetch_event_status(terminal_id:, event_id:)
        validate_presence!(value: terminal_id, name: "terminal_id")
        validate_presence!(value: event_id, name: "event_id")

        handle_response(
          @connection.get("/terminal/#{escape_path(terminal_id, name: "terminal_id")}/event/#{escape_path(event_id, name: "event_id")}")
        )
      end

      # Fetch Terminal Status.
      #
      # Check the availiability of a Terminal before sending an event to it
      #
      # @param terminal_id [String] The ID of the Terminal the event should be sent to.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/terminal/#fetch-terminal-status
      def fetch_status(terminal_id:)
        validate_presence!(value: terminal_id, name: "terminal_id")

        handle_response(
          @connection.get("/terminal/#{escape_path(terminal_id, name: "terminal_id")}/presence")
        )
      end

      # List Terminals.
      #
      # List the Terminals available on your integration
      #
      # @param next_cursor [String] A cursor that indicates your place in the list.
      # @param previous [String] A cursor that indicates your place in the list.
      # @param per_page [Integer] Specify how many records you want to retrieve per page
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/terminal/#list
      def list(next_cursor: nil, previous: nil, per_page: nil)
        validate_positive_integer!(value: per_page, name: "per_page")

        wire_query = to_wire({next_cursor:, previous:, per_page:}, WIRE_NAMES)

        handle_response(@connection.get("/terminal", wire_query))
      end

      # Fetch Terminal.
      #
      # Get the details of a Terminal
      #
      # @param terminal_id [String] The ID of the Terminal the event should be sent to.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/terminal/#fetch
      def fetch(terminal_id:)
        validate_presence!(value: terminal_id, name: "terminal_id")

        handle_response(
          @connection.get("/terminal/#{escape_path(terminal_id, name: "terminal_id")}")
        )
      end

      # Update Terminal.
      #
      # Update the details of a Terminal
      #
      # @param terminal_id [String] The ID of the Terminal the event should be sent to.
      # @param name [String] The new name for the Terminal
      # @param address [String] The new address for the Terminal
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/terminal/#update
      def update(terminal_id:, name: nil, address: nil)
        validate_presence!(value: terminal_id, name: "terminal_id")

        wire_body = to_wire({name:, address:}, WIRE_NAMES)

        handle_response(
          @connection.put("/terminal/#{escape_path(terminal_id, name: "terminal_id")}", wire_body)
        )
      end

      # Commission Terminal.
      #
      # Activate your debug device by linking it to your integration
      #
      # @param serial_number [String] Device Serial Number
      # @note This links a physical device to your integration. Not verified against the Paystack
      #   API: the test account used to build this SDK has no Terminal access.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/terminal/#commission
      def commission(serial_number:)
        validate_presence!(value: serial_number, name: "serial_number")

        wire_body = to_wire({serial_number:}, WIRE_NAMES)

        handle_response(@connection.post("/terminal/commission_device", wire_body))
      end

      # Decommission Terminal.
      #
      # Unlink your debug device from your integration
      #
      # @param serial_number [String] Device Serial Number
      # @note This unlinks a physical device from your integration. Not verified against the
      #   Paystack API: the test account used to build this SDK has no Terminal access.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/terminal/#decommission
      def decommission(serial_number:)
        validate_presence!(value: serial_number, name: "serial_number")

        wire_body = to_wire({serial_number:}, WIRE_NAMES)

        handle_response(@connection.post("/terminal/decommission_device", wire_body))
      end
    end
  end
end
