# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Transfer Recipient`. Hand-written extras go in lib/paystack_sdk/resources/extensions/transfer_recipients.rb.
# scaffold-digest: 74785aa38f6edfebdeff52d47bb3b355c2ad95b2cacdd6c0d7062725415bbfaa

require_relative "base"

module PaystackSdk
  module Resources
    # Transfer Recipient operations.
    class TransferRecipients < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {next_cursor: "next", per_page: "perPage"}.freeze

      # List Transfer Recipients.
      #
      # List transfer recipients available on your integration
      #
      # @param use_cursor [Boolean] A flag to indicate if cursor based pagination should be used
      # @param next_cursor [String] An alphanumeric value returned for every cursor based retrieval, used to retrieve the next set of data
      # @param previous [String] An alphanumeric value returned for every cursor based retrieval, used to retrieve the previous set of data
      # @param per_page [Integer] The number of records to fetch per request
      # @param page [Integer] The offset to retrieve data from
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transfer-recipient/#list
      def list(use_cursor: nil, next_cursor: nil, previous: nil, per_page: nil, page: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire({use_cursor:, next_cursor:, previous:, per_page:, page:}, WIRE_NAMES)

        handle_response(@connection.get("/transferrecipient", wire_query))
      end

      # Create Transfer Recipient.
      #
      # Creates a new recipient. A duplicate account number will lead to the retrieval of the existing record.
      #
      # @param type [String] Recipient Type One of: nuban, ghipss, mobile_money, basa, authorization.
      # @param name [String] The recipient's name according to their account registration.
      # @param account_number [String] Recipient's bank account number
      # @param bank_code [String] Recipient's bank code, from the List Banks endpoint.
      # @param description [String] A description for this recipient
      # @param currency [String] Currency for the account receiving the transfer
      # @param authorization_code [String] An authorization code from a previous transaction
      # @param metadata [Hash] JSON object of custom data
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transfer-recipient/#create
      def create(
        type:,
        name:,
        account_number:,
        bank_code:,
        description: nil,
        currency: nil,
        authorization_code: nil,
        metadata: nil
      )
        validate_presence!(value: type, name: "type")
        validate_allowed_values!(
          value: type,
          allowed_values: %w[nuban ghipss mobile_money basa authorization],
          name: "type"
        )
        validate_presence!(value: name, name: "name")
        validate_presence!(value: account_number, name: "account_number")
        validate_presence!(value: bank_code, name: "bank_code")

        wire_body = to_wire(
          {
            type:,
            name:,
            account_number:,
            bank_code:,
            description:,
            currency:,
            authorization_code:,
            metadata:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/transferrecipient", wire_body))
      end

      # Bulk Create Transfer Recipient.
      #
      # Create multiple transfer recipients in batches. A duplicate account number will lead to the retrieval of the existing record.
      #
      # @param batch [Array<Hash>] A list of transfer recipient objects, each with the fields accepted by {#create}
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transfer-recipient/#bulk
      def bulk_create(batch:)
        validate_presence!(value: batch, name: "batch")

        wire_body = to_wire({batch:}, WIRE_NAMES)

        handle_response(@connection.post("/transferrecipient/bulk", wire_body))
      end

      # Fetch Transfer recipient.
      #
      # Fetch the details of a transfer recipient
      #
      # @param code [String] The recipient code (RCP_...) or numeric ID (Paystack names this path variable id_or_code)
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transfer-recipient/#fetch
      def fetch(code:)
        validate_presence!(value: code, name: "code")

        handle_response(@connection.get("/transferrecipient/#{escape_path(code, name: "code")}"))
      end

      # Update Transfer Recipient.
      #
      # Update the details of a transfer recipient
      #
      # @param code [String] The recipient code (RCP_...) or numeric ID (Paystack names this path variable id_or_code)
      # @param name [String] Recipient's name
      # @param email [String] Recipient's email address
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transfer-recipient/#update
      def update(code:, name: nil, email: nil)
        validate_presence!(value: code, name: "code")
        validate_email!(email: email, name: "email", allow_nil: true)

        wire_body = to_wire({name:, email:}, WIRE_NAMES)

        handle_response(
          @connection.put("/transferrecipient/#{escape_path(code, name: "code")}", wire_body)
        )
      end

      # Delete Transfer Recipient.
      #
      # Delete a transfer recipient (sets the transfer recipient to inactive)
      #
      # @param code [String] The recipient code (RCP_...) or numeric ID (Paystack names this path variable id_or_code)
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transfer-recipient/#delete
      def delete(code:)
        validate_presence!(value: code, name: "code")

        handle_response(@connection.delete("/transferrecipient/#{escape_path(code, name: "code")}"))
      end
    end
  end
end
