# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Transaction`. Hand-written extras go in lib/paystack_sdk/resources/extensions/transactions.rb.
# scaffold-digest: c0b49a40a718c09c83eb9a496eb40d1f7cd4c1387b54efa3cfe360906be89f0e

require_relative "base"

module PaystackSdk
  module Resources
    # Transaction operations.
    class Transactions < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {next_cursor: "next", per_page: "perPage", terminal_id: "terminalid", customer_id: "customer"}.freeze

      # Initialize Transaction.
      #
      # Create a new transaction
      #
      # @param email [String] Customer's email address
      # @param amount [Integer] Amount should be in smallest denomination of the currency.
      # @param currency [String] List of all support currencies One of: GHS, KES, NGN, ZAR, USD.
      # @param reference [String] Unique transaction reference.
      # @param channels [Array] An array of payment channels to control what channels you want to make available to the user to make a payment with
      # @param callback_url [String] Fully qualified url, e.g.
      # @param plan [String] If transaction is to create a subscription to a predefined plan, provide plan code here.
      # @param invoice_limit [Integer] Number of times to charge customer during subscription to plan
      # @param split_code [String] The split code of the transaction split
      # @param split [Hash] Split configuration for transactions
      # @param subaccount [String] The code for the subaccount that owns the payment
      # @param transaction_charge [String] A flat fee to charge the subaccount for a transaction.
      # @param bearer [String] The bearer of the transaction charge One of: account, subaccount.
      # @param label [String] Used to replace the email address shown on the Checkout
      # @param metadata [Hash] JSON object of custom data
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transaction/#initialize
      def initiate(
        email:,
        amount:,
        currency: nil,
        reference: nil,
        channels: nil,
        callback_url: nil,
        plan: nil,
        invoice_limit: nil,
        split_code: nil,
        split: nil,
        subaccount: nil,
        transaction_charge: nil,
        bearer: nil,
        label: nil,
        metadata: nil
      )
        validate_presence!(value: email, name: "email")
        validate_email!(email: email, name: "email")
        validate_presence!(value: amount, name: "amount")
        validate_positive_integer!(value: amount, name: "amount")
        validate_allowed_values!(
          value: currency,
          allowed_values: %w[GHS KES NGN ZAR USD],
          name: "currency"
        )
        validate_reference_format!(reference: reference, name: "reference") unless reference.nil?
        validate_allowed_values!(
          value: bearer,
          allowed_values: %w[account subaccount],
          name: "bearer"
        )

        wire_body = to_wire(
          {
            email:,
            amount:,
            currency:,
            reference:,
            channels:,
            callback_url:,
            plan:,
            invoice_limit:,
            split_code:,
            split:,
            subaccount:,
            transaction_charge:,
            bearer:,
            label:,
            metadata:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/transaction/initialize", wire_body))
      end

      # Charge Authorization.
      #
      # Charge all authorizations marked as reusable with this endpoint whenever you need to receive payments
      #
      # @param email [String] Customer's email address
      # @param amount [Integer] Amount in the lower denomination of your currency
      # @param authorization_code [String] Valid authorization code to charge
      # @param reference [String] Unique transaction reference.
      # @param currency [String] List of all support currencies One of: GHS, KES, NGN, ZAR, USD.
      # @param split_code [String] The split code of the transaction split
      # @param split [Hash] Split configuration for transactions
      # @param subaccount [String] The code for the subaccount that owns the payment
      # @param transaction_charge [String] A flat fee to charge the subaccount for a transaction.
      # @param bearer [String] The bearer of the transaction charge One of: account, subaccount.
      # @param metadata [String] Stringified JSON object of custom data
      # @param queue [Boolean] If you are making a scheduled charge call, it is a good idea to queue them so the processing system does not get overloaded causing transaction processing errors.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transaction/#charge-authorization
      def charge_authorization(
        email:,
        amount:,
        authorization_code:,
        reference: nil,
        currency: nil,
        split_code: nil,
        split: nil,
        subaccount: nil,
        transaction_charge: nil,
        bearer: nil,
        metadata: nil,
        queue: nil
      )
        validate_presence!(value: email, name: "email")
        validate_email!(email: email, name: "email")
        validate_presence!(value: amount, name: "amount")
        validate_positive_integer!(value: amount, name: "amount")
        validate_presence!(value: authorization_code, name: "authorization_code")
        validate_reference_format!(reference: reference, name: "reference") unless reference.nil?
        validate_allowed_values!(
          value: currency,
          allowed_values: %w[GHS KES NGN ZAR USD],
          name: "currency"
        )
        validate_allowed_values!(
          value: bearer,
          allowed_values: %w[account subaccount],
          name: "bearer"
        )

        wire_body = to_wire(
          {
            email:,
            amount:,
            authorization_code:,
            reference:,
            currency:,
            split_code:,
            split:,
            subaccount:,
            transaction_charge:,
            bearer:,
            metadata: stringify_json(metadata),
            queue:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/transaction/charge_authorization", wire_body))
      end

      # Partial Debit.
      #
      # Retrieve part of a payment from a customer
      #
      # @param email [String] Customer's email address
      # @param amount [Integer] Specified in the lowest denomination of your currency
      # @param authorization_code [String] Valid authorization code to charge
      # @param currency [String] List of all support currencies One of: GHS, KES, NGN, ZAR, USD.
      # @param at_least [String] Minimum amount to charge
      # @param reference [String] Unique transaction reference.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transaction/#partial-debit
      def partial_debit(
        email:,
        amount:,
        authorization_code:,
        currency:,
        at_least: nil,
        reference: nil
      )
        validate_presence!(value: email, name: "email")
        validate_email!(email: email, name: "email")
        validate_presence!(value: amount, name: "amount")
        validate_positive_integer!(value: amount, name: "amount")
        validate_presence!(value: authorization_code, name: "authorization_code")
        validate_presence!(value: currency, name: "currency")
        validate_allowed_values!(
          value: currency,
          allowed_values: %w[GHS KES NGN ZAR USD],
          name: "currency"
        )
        validate_reference_format!(reference: reference, name: "reference") unless reference.nil?

        wire_body = to_wire(
          {
            email:,
            amount:,
            authorization_code:,
            currency:,
            at_least:,
            reference:
          },
          WIRE_NAMES
        )

        handle_response(@connection.post("/transaction/partial_debit", wire_body))
      end

      # Verify Transaction.
      #
      # Verify a previously initiated transaction using it's reference
      #
      # @param reference [String] The transaction reference to verify
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transaction/#verify
      def verify(reference:)
        validate_presence!(value: reference, name: "reference")

        handle_response(
          @connection.get("/transaction/verify/#{escape_path(reference, name: "reference")}")
        )
      end

      # List Transactions.
      #
      # List transactions that has occurred on your integration
      #
      # @param use_cursor [Boolean] A flag to indicate if cursor based pagination should be used
      # @param next_cursor [String] An alphanumeric value returned for every cursor based retrieval, used to retrieve the next set of data
      # @param previous [String] An alphanumeric value returned for every cursor based retrieval, used to retrieve the previous set of data
      # @param per_page [Integer] The number of records to fetch per request
      # @param page [Integer] The offset to retrieve data from
      # @param from [String] The start date
      # @param to [String] The end date
      # @param status [String] Filter transaction by status One of: success, failed, abandoned, reversed.
      # @param source [String] The origin of the payment One of: merchantApi, checkout, pos, virtualTerminal.
      # @param terminal_id [String] Filter transactions by a terminal ID
      # @param virtual_account_number [String] Filter transactions by a virtual account number
      # @param customer_id [Integer] Filter transactions by a customer code
      # @param amount [Integer] Filter transactions by a specific amount
      # @param settlement [Integer] The settlement ID to filter for settled transactions
      # @param channel [String] The payment method the customer used to complete the transaction One of: card, pos, bank, dedicated_nuban, ussd, bank_transfer.
      # @param subaccount_code [String] Filter transaction by subaccount code
      # @param split_code [String] Filter transaction by split code
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transaction/#list
      def list(
        use_cursor: nil,
        next_cursor: nil,
        previous: nil,
        per_page: nil,
        page: nil,
        from: nil,
        to: nil,
        status: nil,
        source: nil,
        terminal_id: nil,
        virtual_account_number: nil,
        customer_id: nil,
        amount: nil,
        settlement: nil,
        channel: nil,
        subaccount_code: nil,
        split_code: nil
      )
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")
        validate_allowed_values!(
          value: status,
          allowed_values: %w[success failed abandoned reversed],
          name: "status"
        )
        validate_allowed_values!(
          value: source,
          allowed_values: %w[merchantApi checkout pos virtualTerminal],
          name: "source"
        )
        validate_positive_integer!(value: amount, name: "amount")
        validate_allowed_values!(
          value: channel,
          allowed_values: %w[card pos bank dedicated_nuban ussd bank_transfer],
          name: "channel"
        )

        wire_query = to_wire(
          {
            use_cursor:,
            next_cursor:,
            previous:,
            per_page:,
            page:,
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to"),
            status:,
            source:,
            terminal_id:,
            virtual_account_number:,
            customer_id:,
            amount:,
            settlement:,
            channel:,
            subaccount_code:,
            split_code:
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/transaction", wire_query))
      end

      # Fetch Transaction.
      #
      # Fetch a transaction to get its details
      #
      # @param id [Integer] The ID of the transaction to fetch
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transaction/#fetch
      def fetch(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/transaction/#{escape_path(id, name: "id")}"))
      end

      # Fetch Transaction Timeline.
      #
      # Fetch the steps taken from the initiation to the completion of a transaction
      #
      # @param id [Integer] The ID of the transaction to fetch
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transaction/#view-timeline
      def timeline(id:)
        validate_presence!(value: id, name: "id")

        handle_response(@connection.get("/transaction/timeline/#{escape_path(id, name: "id")}"))
      end

      # Transaction Totals.
      #
      # Get the total amount of all transactions
      #
      # @param from [String] The start date
      # @param to [String] The end date
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transaction/#totals
      def totals(from: nil, to: nil)
        wire_query = to_wire(
          {
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to")
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/transaction/totals", wire_query))
      end

      # Export Transactions.
      #
      # Download transactions that occurred on your integration for a specific timeframe
      #
      # @param from [String] The start date
      # @param to [String] The end date
      # @param status [String] Filter by the status of the transaction One of: success, failed, abandoned, reversed, all.
      # @param customer_id [Numeric] Filter by customer ID
      # @param subaccount_code [String] Filter by subaccount code
      # @param settlement [Integer] Filter by the settlement ID
      # @param currency [String] Specify the transaction currency to export.
      # @param amount [Integer] Filter transactions by amount, using the supported currency subunit.
      # @param settled [Boolean] Set to true to export only settled transactions, false for pending transactions.
      # @param payment_page [Integer] Specify a payment page's id to export only transactions conducted on said page.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/transaction/#export
      def export(
        from: nil,
        to: nil,
        status: nil,
        customer_id: nil,
        subaccount_code: nil,
        settlement: nil,
        currency: nil,
        amount: nil,
        settled: nil,
        payment_page: nil
      )
        validate_allowed_values!(
          value: status,
          allowed_values: %w[success failed abandoned reversed all],
          name: "status"
        )
        validate_positive_integer!(value: amount, name: "amount")

        wire_query = to_wire(
          {
            from: format_datetime(from, name: "from"),
            to: format_datetime(to, name: "to"),
            status:,
            customer_id:,
            subaccount_code:,
            settlement:,
            currency:,
            amount:,
            settled:,
            payment_page:
          },
          WIRE_NAMES
        )

        handle_response(@connection.get("/transaction/export", wire_query))
      end
    end
  end
end
