# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Virtual Terminal`. Hand-written extras go in lib/paystack_sdk/resources/extensions/virtual_terminals.rb.
# scaffold-digest: 9302433893249a59feb8c11b215838d8364c0cb4e51090af609d1dfab2a656d4

require_relative "base"

module PaystackSdk
  module Resources
    # Virtual Terminal operations.
    class VirtualTerminals < PaystackSdk::Resources::Base
      # Ruby keyword => the parameter name Paystack documents.
      WIRE_NAMES = {per_page: "perPage"}.freeze

      # List Virtual Terminals.
      #
      # List Virtual Terminals on your integration
      #
      # @param per_page [Integer] The number of records to fetch per request
      # @param page [Integer] The offset to retrieve data from
      # @param status [String] Filter virtual terminals by status, active or inactive.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/virtual-terminal/#list
      def list(per_page: nil, page: nil, status: nil)
        validate_positive_integer!(value: per_page, name: "perPage")
        validate_positive_integer!(value: page, name: "page")

        wire_query = to_wire({per_page:, page:, status:}, WIRE_NAMES)

        handle_response(@connection.get("/virtual_terminal", wire_query))
      end

      # Create Virtual Terminal.
      #
      # Create a Virtual Terminal on your integration
      #
      # @param name [String] The name of the virtual terminal
      # @param destinations [Array] Array of objects containing recipients for payment notifications for the Virtual Terminal.
      # @param split_code [String] Split code to associate with the virtual terminal
      # @param metadata [Hash] Additional custom data as key-value pairs
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/virtual-terminal/#create
      def create(name:, destinations:, split_code: nil, metadata: nil)
        validate_presence!(value: name, name: "name")
        validate_presence!(value: destinations, name: "destinations")

        wire_body = to_wire({name:, destinations:, split_code:, metadata:}, WIRE_NAMES)

        handle_response(@connection.post("/virtual_terminal", wire_body))
      end

      # Fetch Virtual Terminal.
      #
      # Fetch a Virtual Terminal on your integration
      #
      # @param code [String] Code of the Virtual Terminal
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/virtual-terminal/#fetch
      def fetch(code:)
        validate_presence!(value: code, name: "code")

        handle_response(@connection.get("/virtual_terminal/#{escape_path(code, name: "code")}"))
      end

      # Update Virtual Terminal.
      #
      # Update a Virtual Terminal on your integration
      #
      # @param code [String] Code of the Virtual Terminal
      # @param name [String] Name of the virtual terminal
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/virtual-terminal/#update
      def update(code:, name:)
        validate_presence!(value: code, name: "code")
        validate_presence!(value: name, name: "name")

        wire_body = to_wire({name:}, WIRE_NAMES)

        handle_response(
          @connection.put("/virtual_terminal/#{escape_path(code, name: "code")}", wire_body)
        )
      end

      # Deactivate Virtual Terminal.
      #
      # Deactivate a Virtual Terminal on your integration
      #
      # @param code [String] Code of the Virtual Terminal
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/virtual-terminal/#deactivate
      def deactivate(code:)
        validate_presence!(value: code, name: "code")

        handle_response(
          @connection.put("/virtual_terminal/#{escape_path(code, name: "code")}/deactivate")
        )
      end

      # Assign Destination to Virtual Terminal.
      #
      # Add a destination (WhatsApp number) to a Virtual Terminal on your integration
      #
      # @param code [String] Code of the Virtual Terminal
      # @param destinations [Array] Array of objects containing recipients for payment notifications for the Virtual Terminal.
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/virtual-terminal/#assign-destination
      def assign_destination(code:, destinations:)
        validate_presence!(value: code, name: "code")
        validate_presence!(value: destinations, name: "destinations")

        wire_body = to_wire({destinations:}, WIRE_NAMES)

        handle_response(
          @connection.post("/virtual_terminal/#{escape_path(code, name: "code")}/destination/assign", wire_body)
        )
      end

      # Unassign Destination from Virtual Terminal.
      #
      # Unassign a destination (WhatsApp Number) from a Virtual Terminal on your integration
      #
      # @param code [String] Code of the Virtual Terminal
      # @param targets [Array] Array of destination targets to unassign
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/virtual-terminal/#unassign-destination
      def unassign_destination(code:, targets:)
        validate_presence!(value: code, name: "code")
        validate_presence!(value: targets, name: "targets")

        wire_body = to_wire({targets:}, WIRE_NAMES)

        handle_response(
          @connection.post("/virtual_terminal/#{escape_path(code, name: "code")}/destination/unassign", wire_body)
        )
      end

      # Add Split Code to Virtual Terminal.
      #
      # Add Split Code to Virtual Terminal
      #
      # @param code [String] Code of the Virtual Terminal
      # @param split_code [String] The split code to assign to the virtual terminal
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/virtual-terminal/#add-split-code
      def add_split_code(code:, split_code:)
        validate_presence!(value: code, name: "code")
        validate_presence!(value: split_code, name: "split_code")

        wire_body = to_wire({split_code:}, WIRE_NAMES)

        handle_response(
          @connection.put("/virtual_terminal/#{escape_path(code, name: "code")}/split_code", wire_body)
        )
      end

      # Remove Split Code from Virtual Terminal.
      #
      # Remove Split Code from Virtual Terminal
      #
      # @param code [String] Code of the Virtual Terminal
      # @param split_code [String] The split code to assign to the virtual terminal
      # @return [PaystackSdk::Response] The response from the Paystack API.
      # @raise [PaystackSdk::Error] If a parameter is invalid or the API request fails.
      # @see https://paystack.com/docs/api/virtual-terminal/#remove-split-code
      def remove_split_code(code:, split_code:)
        validate_presence!(value: code, name: "code")
        validate_presence!(value: split_code, name: "split_code")

        wire_body = to_wire({split_code:}, WIRE_NAMES)

        handle_response(
          @connection.delete("/virtual_terminal/#{escape_path(code, name: "code")}/split_code") { |request| request.body = wire_body }
        )
      end
    end
  end
end
