# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Apple Pay`.
# scaffold-digest: eef05705f5adbf212813550755ed6aa9b93bfb50d880ef23df551374e211f99b

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::ApplePay do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list_domains" do
    it "sends GET /apple-pay/domain as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/apple-pay/domain")
        .to_return(ok)

      response = resource.list_domains

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#register_domain" do
    it "sends POST /apple-pay/domain as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/apple-pay/domain")
        .to_return(ok)

      response = resource.register_domain(domain_name: "sample_domainName")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires domain_name" do
      expect do
        resource.register_domain
      end.to raise_error(ArgumentError, /domain_name/)
    end
  end

  describe "#unregister_domain" do
    it "sends DELETE /apple-pay/domain as Paystack documents it" do
      stub = stub_request(:delete, "https://api.paystack.co/apple-pay/domain")
        .to_return(ok)

      response = resource.unregister_domain(domain_name: "sample_domainName")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires domain_name" do
      expect do
        resource.unregister_domain
      end.to raise_error(ArgumentError, /domain_name/)
    end
  end
end
