# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Balance`.
# scaffold-digest: f779504f59174033c068e27505a1144870a3c9a0cfe95fbe2483d090d25fc54b

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Balances do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#fetch" do
    it "sends GET /balance as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/balance")
        .to_return(ok)

      response = resource.fetch

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#ledger" do
    it "sends GET /balance/ledger as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/balance/ledger")
        .to_return(ok)

      response = resource.ledger

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
