# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Bank`.
# scaffold-digest: 6502772649b93c0dd4ca7eca6d086da477b86cab0bbbb091a5ad43c3b854a410

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Banks do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /bank as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/bank")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#resolve_account_number" do
    it "sends GET /bank/resolve as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/bank/resolve")
        .with(query: {"account_number" => "1", "bank_code" => "1"})
        .to_return(ok)

      response = resource.resolve_account_number(account_number: 1, bank_code: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires account_number" do
      expect do
        resource.resolve_account_number(bank_code: 1)
      end.to raise_error(ArgumentError, /account_number/)
    end
  end

  describe "#validate_account" do
    it "sends POST /bank/validate as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/bank/validate")
        .to_return(ok)

      response = resource.validate_account(
        account_name: "sample_account_name",
        account_number: "sample_account_number",
        account_type: "personal",
        bank_code: "sample_bank_code",
        country_code: "sample_country_code",
        document_type: "identityNumber"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires account_name" do
      expect do
        resource.validate_account(
          account_number: "sample_account_number",
          account_type: "personal",
          bank_code: "sample_bank_code",
          country_code: "sample_country_code",
          document_type: "identityNumber"
        )
      end.to raise_error(ArgumentError, /account_name/)
    end
  end
end
