# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Bulk Charge`.
# scaffold-digest: 1dfeab2fae3210524cea38360fc07ef387d150cc8bf8336a931bd6370ad1ee39

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::BulkCharges do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list_batches" do
    it "sends GET /bulkcharge as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/bulkcharge")
        .to_return(ok)

      response = resource.list_batches

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#initiate" do
    it "sends POST /bulkcharge as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/bulkcharge")
        .to_return(ok)

      response = resource.initiate(
        charges: [{"authorization" => "AUTH_ncx8hews93", "amount" => 250000, "reference" => "dam1266638dhhd"}]
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires charges" do
      expect do
        resource.initiate
      end.to raise_error(ArgumentError, /charges/)
    end
  end

  describe "#fetch_batch" do
    it "sends GET /bulkcharge/{code} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/bulkcharge/sample_code")
        .to_return(ok)

      response = resource.fetch_batch(id_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#fetch_charges" do
    it "sends GET /bulkcharge/{code}/charges as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/bulkcharge/sample_code/charges")
        .to_return(ok)

      response = resource.fetch_charges(id_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#pause_batch" do
    it "sends GET /bulkcharge/pause/{code} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/bulkcharge/pause/sample_code")
        .to_return(ok)

      response = resource.pause_batch(batch_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#resume_batch" do
    it "sends GET /bulkcharge/resume/{code} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/bulkcharge/resume/sample_code")
        .to_return(ok)

      response = resource.resume_batch(batch_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
