# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Charge`.
# scaffold-digest: 5b7f3c08f1dacbd350814648d0a7d1098e20e00109f8645d527b7ce44078ef10

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Charges do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#create" do
    it "sends POST /charge as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/charge")
        .to_return(ok)

      response = resource.create(email: "ama@example.com", amount: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires email" do
      expect do
        resource.create(amount: 1)
      end.to raise_error(ArgumentError, /email/)
    end
  end

  describe "#submit_pin" do
    it "sends POST /charge/submit_pin as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/charge/submit_pin")
        .to_return(ok)

      response = resource.submit_pin(pin: "sample_pin", reference: "sample-reference")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires pin" do
      expect do
        resource.submit_pin(reference: "sample-reference")
      end.to raise_error(ArgumentError, /pin/)
    end
  end

  describe "#submit_otp" do
    it "sends POST /charge/submit_otp as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/charge/submit_otp")
        .to_return(ok)

      response = resource.submit_otp(otp: "sample_otp", reference: "sample-reference")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires otp" do
      expect do
        resource.submit_otp(reference: "sample-reference")
      end.to raise_error(ArgumentError, /otp/)
    end
  end

  describe "#submit_phone" do
    it "sends POST /charge/submit_phone as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/charge/submit_phone")
        .to_return(ok)

      response = resource.submit_phone(phone: "sample_phone", reference: "sample-reference")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires phone" do
      expect do
        resource.submit_phone(reference: "sample-reference")
      end.to raise_error(ArgumentError, /phone/)
    end
  end

  describe "#submit_birthday" do
    it "sends POST /charge/submit_birthday as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/charge/submit_birthday")
        .to_return(ok)

      response = resource.submit_birthday(birthday: "2026-01-31", reference: "sample-reference")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires birthday" do
      expect do
        resource.submit_birthday(reference: "sample-reference")
      end.to raise_error(ArgumentError, /birthday/)
    end
  end

  describe "#submit_address" do
    it "sends POST /charge/submit_address as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/charge/submit_address")
        .to_return(ok)

      response = resource.submit_address(
        address: "sample_address",
        city: "sample_city",
        state: "sample_state",
        zip_code: "sample_zip_code",
        reference: "sample-reference"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires address" do
      expect do
        resource.submit_address(
          city: "sample_city",
          state: "sample_state",
          zip_code: "sample_zip_code",
          reference: "sample-reference"
        )
      end.to raise_error(ArgumentError, /address/)
    end
  end

  describe "#check_pending" do
    it "sends GET /charge/{reference} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/charge/sample-reference")
        .to_return(ok)

      response = resource.check_pending(reference: "sample-reference")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
