# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Customer`.
# scaffold-digest: 5ed6f03cb73fed916cfb5fcf8b5478cc38fb31593f58500c0860bc53db9ca81f

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Customers do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /customer as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/customer")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /customer as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/customer")
        .to_return(ok)

      response = resource.create(email: "ama@example.com")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires email" do
      expect do
        resource.create
      end.to raise_error(ArgumentError, /email/)
    end
  end

  describe "#fetch" do
    it "sends GET /customer/{code} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/customer/sample_code")
        .to_return(ok)

      response = resource.fetch(email_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /customer/{code} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/customer/sample_code")
        .to_return(ok)

      response = resource.update(code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#set_risk_action" do
    it "sends POST /customer/set_risk_action as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/customer/set_risk_action")
        .to_return(ok)

      response = resource.set_risk_action(customer: "sample_customer")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires customer" do
      expect do
        resource.set_risk_action
      end.to raise_error(ArgumentError, /customer/)
    end
  end

  describe "#validate" do
    it "sends POST /customer/{code}/identification as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/customer/sample_code/identification")
        .to_return(ok)

      response = resource.validate(
        code: "sample_code",
        first_name: "sample_first_name",
        last_name: "sample_last_name",
        type: "sample_type",
        country: "sample_country",
        bvn: "sample_bvn",
        bank_code: "sample_bank_code",
        account_number: "sample_account_number"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires first_name" do
      expect do
        resource.validate(
          code: "sample_code",
          last_name: "sample_last_name",
          type: "sample_type",
          country: "sample_country",
          bvn: "sample_bvn",
          bank_code: "sample_bank_code",
          account_number: "sample_account_number"
        )
      end.to raise_error(ArgumentError, /first_name/)
    end
  end

  describe "#initialize_authorization" do
    it "sends POST /customer/authorization/initialize as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/customer/authorization/initialize")
        .to_return(ok)

      response = resource.initialize_authorization(
        email: "ama@example.com",
        channel: "direct_debit"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires email" do
      expect do
        resource.initialize_authorization(channel: "direct_debit")
      end.to raise_error(ArgumentError, /email/)
    end
  end

  describe "#verify_authorization" do
    it "sends GET /customer/authorization/verify/{reference} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/customer/authorization/verify/sample-reference")
        .to_return(ok)

      response = resource.verify_authorization(reference: "sample-reference")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#deactivate_authorization" do
    it "sends POST /customer/authorization/deactivate as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/customer/authorization/deactivate")
        .to_return(ok)

      response = resource.deactivate_authorization(authorization_code: "sample_authorization_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires authorization_code" do
      expect do
        resource.deactivate_authorization
      end.to raise_error(ArgumentError, /authorization_code/)
    end
  end

  describe "#initialize_direct_debit" do
    it "sends POST /customer/{id}/initialize-direct-debit as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/customer/1/initialize-direct-debit")
        .to_return(ok)

      response = resource.initialize_direct_debit(
        id: 1,
        account: {"number" => "0123456789", "bank_code" => "058"},
        address: {"street" => "Some Where", "city" => "Ikeja", "state" => "Lagos"}
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires account" do
      expect do
        resource.initialize_direct_debit(
          id: 1,
          address: {"street" => "Some Where", "city" => "Ikeja", "state" => "Lagos"}
        )
      end.to raise_error(ArgumentError, /account/)
    end
  end

  describe "#direct_debit_activation_charge" do
    it "sends PUT /customer/{id}/directdebit-activation-charge as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/customer/1/directdebit-activation-charge")
        .to_return(ok)

      response = resource.direct_debit_activation_charge(id: 1, authorization_id: 1069309917)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires authorization_id" do
      expect do
        resource.direct_debit_activation_charge(id: 1)
      end.to raise_error(ArgumentError, /authorization_id/)
    end
  end

  describe "#fetch_mandate_authorizations" do
    it "sends GET /customer/{id}/directdebit-mandate-authorizations as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/customer/1/directdebit-mandate-authorizations")
        .to_return(ok)

      response = resource.fetch_mandate_authorizations(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
