# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Dedicated Virtual Account`.
# scaffold-digest: 769526e8253bf06ed5a85573b8df4cf1d5e108cd6925481a1cdab18c2ba35a26

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::DedicatedVirtualAccounts do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /dedicated_account as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/dedicated_account")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /dedicated_account as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/dedicated_account")
        .to_return(ok)

      response = resource.create(customer: "sample_customer")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires customer" do
      expect do
        resource.create
      end.to raise_error(ArgumentError, /customer/)
    end
  end

  describe "#assign" do
    it "sends POST /dedicated_account/assign as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/dedicated_account/assign")
        .to_return(ok)

      response = resource.assign(
        email: "ama@example.com",
        first_name: "sample_first_name",
        last_name: "sample_last_name",
        phone: "sample_phone",
        preferred_bank: "sample_preferred_bank",
        country: "NG"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires email" do
      expect do
        resource.assign(
          first_name: "sample_first_name",
          last_name: "sample_last_name",
          phone: "sample_phone",
          preferred_bank: "sample_preferred_bank",
          country: "NG"
        )
      end.to raise_error(ArgumentError, /email/)
    end
  end

  describe "#fetch" do
    it "sends GET /dedicated_account/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/dedicated_account/sample_id")
        .to_return(ok)

      response = resource.fetch(dedicated_account_id: "sample_id")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#deactivate" do
    it "sends DELETE /dedicated_account/{id} as Paystack documents it" do
      stub = stub_request(:delete, "https://api.paystack.co/dedicated_account/sample_id")
        .to_return(ok)

      response = resource.deactivate(dedicated_account_id: "sample_id")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#requery" do
    it "sends GET /dedicated_account/requery as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/dedicated_account/requery")
        .to_return(ok)

      response = resource.requery

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#add_split" do
    it "sends POST /dedicated_account/split as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/dedicated_account/split")
        .to_return(ok)

      response = resource.add_split(account_number: "sample_account_number")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires account_number" do
      expect do
        resource.add_split
      end.to raise_error(ArgumentError, /account_number/)
    end
  end

  describe "#remove_split" do
    it "sends DELETE /dedicated_account/split as Paystack documents it" do
      stub = stub_request(:delete, "https://api.paystack.co/dedicated_account/split")
        .to_return(ok)

      response = resource.remove_split(account_number: "sample_account_number")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires account_number" do
      expect do
        resource.remove_split
      end.to raise_error(ArgumentError, /account_number/)
    end
  end

  describe "#fetch_bank_providers" do
    it "sends GET /dedicated_account/available_providers as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/dedicated_account/available_providers")
        .to_return(ok)

      response = resource.fetch_bank_providers

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
