# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Direct Debit`.
# scaffold-digest: 105d5d69c1cfd22df14525a66fd5b241eb925bc810945a86e7bfcf6f30f5c468

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::DirectDebits do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#trigger_activation_charge" do
    it "sends PUT /directdebit/activation-charge as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/directdebit/activation-charge")
        .to_return(ok)

      response = resource.trigger_activation_charge(customer_ids: [28958104, 983697220])

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires customer_ids" do
      expect do
        resource.trigger_activation_charge
      end.to raise_error(ArgumentError, /customer_ids/)
    end
  end

  describe "#list_mandate_authorizations" do
    it "sends GET /directdebit/mandate-authorizations as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/directdebit/mandate-authorizations")
        .to_return(ok)

      response = resource.list_mandate_authorizations

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
