# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Dispute`.
# scaffold-digest: 490badec377367f8f4f934cbc9a040bf1871905607e07317cbbf743dd8e59ce3

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Disputes do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /dispute as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/dispute")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#fetch" do
    it "sends GET /dispute/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/dispute/1")
        .to_return(ok)

      response = resource.fetch(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /dispute/{id} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/dispute/1")
        .to_return(ok)

      response = resource.update(id: 1, refund_amount: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires refund_amount" do
      expect do
        resource.update(id: 1)
      end.to raise_error(ArgumentError, /refund_amount/)
    end
  end

  describe "#fetch_upload_url" do
    it "sends GET /dispute/{id}/upload_url as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/dispute/1/upload_url")
        .to_return(ok)

      response = resource.fetch_upload_url(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#export" do
    it "sends GET /dispute/export as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/dispute/export")
        .to_return(ok)

      response = resource.export

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#list_transaction" do
    it "sends GET /dispute/transaction/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/dispute/transaction/1")
        .to_return(ok)

      response = resource.list_transaction(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#resolve" do
    it "sends PUT /dispute/{id}/resolve as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/dispute/1/resolve")
        .to_return(ok)

      response = resource.resolve(
        id: 1,
        resolution: "sample_resolution",
        message: "sample_message",
        refund_amount: 1,
        uploaded_filename: "sample_uploaded_filename"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires resolution" do
      expect do
        resource.resolve(
          id: 1,
          message: "sample_message",
          refund_amount: 1,
          uploaded_filename: "sample_uploaded_filename"
        )
      end.to raise_error(ArgumentError, /resolution/)
    end
  end

  describe "#add_evidence" do
    it "sends POST /dispute/{id}/evidence as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/dispute/1/evidence")
        .to_return(ok)

      response = resource.add_evidence(
        id: 1,
        customer_email: "sample_customer_email",
        customer_name: "sample_customer_name",
        customer_phone: "sample_customer_phone",
        service_details: "sample_service_details"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires customer_email" do
      expect do
        resource.add_evidence(
          id: 1,
          customer_name: "sample_customer_name",
          customer_phone: "sample_customer_phone",
          service_details: "sample_service_details"
        )
      end.to raise_error(ArgumentError, /customer_email/)
    end
  end
end
