# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Integration`.
# scaffold-digest: 280c6619b94aaf57eaa8832ae7c97fb61ad19c23bd3848350664296a9d65ebb5

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Integrations do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#fetch_payment_session_timeout" do
    it "sends GET /integration/payment_session_timeout as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/integration/payment_session_timeout")
        .to_return(ok)

      response = resource.fetch_payment_session_timeout

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update_payment_session_timeout" do
    it "sends PUT /integration/payment_session_timeout as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/integration/payment_session_timeout")
        .to_return(ok)

      response = resource.update_payment_session_timeout(timeout: 30)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires timeout" do
      expect do
        resource.update_payment_session_timeout
      end.to raise_error(ArgumentError, /timeout/)
    end
  end
end
