# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Miscellaneous`.
# scaffold-digest: e7b1662fa74ffffb4e7bd9f35a9ae9ac5a9f5f449ed91a86d9fd7e5676f239ea

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Miscellaneous do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#resolve_card_bin" do
    it "sends GET /decision/bin/{bin} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/decision/bin/1")
        .to_return(ok)

      response = resource.resolve_card_bin(bin: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#list_countries" do
    it "sends GET /country as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/country")
        .to_return(ok)

      response = resource.list_countries

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#list_states" do
    it "sends GET /address_verification/states as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/address_verification/states")
        .with(query: {"country" => "sample_country"})
        .to_return(ok)

      response = resource.list_states(country: "sample_country")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires country" do
      expect do
        resource.list_states
      end.to raise_error(ArgumentError, /country/)
    end
  end
end
