# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Order`.
# scaffold-digest: dcce81bb10a626d83b4cae34b62cbe7a353909d162b5d40a6703ee123a3c5320

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Orders do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /order as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/order")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /order as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/order")
        .to_return(ok)

      response = resource.create(
        email: "ama@example.com",
        first_name: "sample_first_name",
        last_name: "sample_last_name",
        phone: "sample_phone",
        currency: "GHS",
        items: [{"item" => 2179824, "type" => "product", "quantity" => 200000, "amount" => 2}],
        shipping: {"street_line" => "Somewhere on Earth", "city" => "Atlantic", "state" => "Pacific", "country" => "Equator", "shipping_fee" => 10000}
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires email" do
      expect do
        resource.create(
          first_name: "sample_first_name",
          last_name: "sample_last_name",
          phone: "sample_phone",
          currency: "GHS",
          items: [{"item" => 2179824, "type" => "product", "quantity" => 200000, "amount" => 2}],
          shipping: {"street_line" => "Somewhere on Earth", "city" => "Atlantic", "state" => "Pacific", "country" => "Equator", "shipping_fee" => 10000}
        )
      end.to raise_error(ArgumentError, /email/)
    end
  end

  describe "#fetch" do
    it "sends GET /order/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/order/1")
        .to_return(ok)

      response = resource.fetch(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#fetch_product_orders" do
    it "sends GET /order/product/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/order/product/1")
        .to_return(ok)

      response = resource.fetch_product_orders(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#validate" do
    it "sends GET /order/{code}/validate as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/order/sample_code/validate")
        .to_return(ok)

      response = resource.validate(code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
