# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Page`.
# scaffold-digest: 90cc592ddb9c62d6bd4471dcaf272e49fe6e423862db65bdb5f9110dcf3e221c

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Pages do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /page as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/page")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /page as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/page")
        .to_return(ok)

      response = resource.create(name: "sample_name")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires name" do
      expect do
        resource.create
      end.to raise_error(ArgumentError, /name/)
    end
  end

  describe "#fetch" do
    it "sends GET /page/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/page/1")
        .to_return(ok)

      response = resource.fetch(id_or_slug: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /page/{id} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/page/1")
        .to_return(ok)

      response = resource.update(id_or_slug: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#check_slug_availability" do
    it "sends GET /page/check_slug_availability/{slug} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/page/check_slug_availability/sample_slug")
        .to_return(ok)

      response = resource.check_slug_availability(slug: "sample_slug")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#add_products" do
    it "sends POST /page/{id}/product as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/page/sample_id/product")
        .to_return(ok)

      response = resource.add_products(id: "sample_id", products: [1])

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires products" do
      expect do
        resource.add_products(id: "sample_id")
      end.to raise_error(ArgumentError, /products/)
    end
  end
end
