# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Payment Request`.
# scaffold-digest: af87bbbe731ed01fea7348f18fc5e709c636cdaab4a522d19266a232eb17d8e5

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::PaymentRequests do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /paymentrequest as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/paymentrequest")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /paymentrequest as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/paymentrequest")
        .to_return(ok)

      response = resource.create(customer: "sample_customer")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires customer" do
      expect do
        resource.create
      end.to raise_error(ArgumentError, /customer/)
    end
  end

  describe "#fetch" do
    it "sends GET /paymentrequest/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/paymentrequest/1")
        .to_return(ok)

      response = resource.fetch(id_or_code: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /paymentrequest/{id} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/paymentrequest/1")
        .to_return(ok)

      response = resource.update(id_or_code: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#verify" do
    it "sends GET /paymentrequest/verify/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/paymentrequest/verify/1")
        .to_return(ok)

      response = resource.verify(code: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#notify" do
    it "sends POST /paymentrequest/notify/{id} as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/paymentrequest/notify/1")
        .to_return(ok)

      response = resource.notify(code: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#totals" do
    it "sends GET /paymentrequest/totals as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/paymentrequest/totals")
        .to_return(ok)

      response = resource.totals

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#finalize" do
    it "sends POST /paymentrequest/finalize/{id} as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/paymentrequest/finalize/1")
        .to_return(ok)

      response = resource.finalize(id_or_code: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#archive" do
    it "sends POST /paymentrequest/archive/{id} as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/paymentrequest/archive/1")
        .to_return(ok)

      response = resource.archive(id_or_code: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
