# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Plan`.
# scaffold-digest: 8ec93177448987ed864c94617000dbe27041b9dcef96079c7969b0985acf0a8b

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Plans do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /plan as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/plan")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /plan as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/plan")
        .to_return(ok)

      response = resource.create(name: "sample_name", amount: 1, interval: "daily")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires name" do
      expect do
        resource.create(amount: 1, interval: "daily")
      end.to raise_error(ArgumentError, /name/)
    end
  end

  describe "#fetch" do
    it "sends GET /plan/{code} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/plan/sample_code")
        .to_return(ok)

      response = resource.fetch(id_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /plan/{code} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/plan/sample_code")
        .to_return(ok)

      response = resource.update(id_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
