# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Product`.
# scaffold-digest: fab50cda092315161798659473a06fc8bc50f937545d6281bd0e246e28d8cc43

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Products do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /product as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/product")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /product as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/product")
        .to_return(ok)

      response = resource.create(name: "sample_name", price: 1, currency: "sample_currency")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires name" do
      expect do
        resource.create(price: 1, currency: "sample_currency")
      end.to raise_error(ArgumentError, /name/)
    end
  end

  describe "#fetch" do
    it "sends GET /product/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/product/1")
        .to_return(ok)

      response = resource.fetch(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /product/{id} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/product/1")
        .to_return(ok)

      response = resource.update(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#delete" do
    it "sends DELETE /product/{id} as Paystack documents it" do
      stub = stub_request(:delete, "https://api.paystack.co/product/1")
        .to_return(ok)

      response = resource.delete(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
