# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Refund`.
# scaffold-digest: 8bc95b1b6e510cfaf7bc3781980182bb85dd7a4491e1f514e06efce0164b84e2

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Refunds do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /refund as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/refund")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /refund as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/refund")
        .to_return(ok)

      response = resource.create(transaction: "sample_transaction")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires transaction" do
      expect do
        resource.create
      end.to raise_error(ArgumentError, /transaction/)
    end
  end

  describe "#retry_with_customer_details" do
    it "sends POST /refund/retry_with_customer_details/{id} as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/refund/retry_with_customer_details/1")
        .to_return(ok)

      response = resource.retry_with_customer_details(
        id: 1,
        refund_account_details: {"currency" => "NGN", "account_number" => "1234567890", "bank_id" => "9"}
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires refund_account_details" do
      expect do
        resource.retry_with_customer_details(id: 1)
      end.to raise_error(ArgumentError, /refund_account_details/)
    end
  end

  describe "#fetch" do
    it "sends GET /refund/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/refund/1")
        .to_return(ok)

      response = resource.fetch(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
