# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Settlement`.
# scaffold-digest: eb5117605a8178989e19960a7002dce664d2bf1cc39f4b3a98ff7763503af3a8

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Settlements do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /settlement as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/settlement")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#transactions" do
    it "sends GET /settlement/{id}/transactions as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/settlement/1/transactions")
        .to_return(ok)

      response = resource.transactions(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
