# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Split`.
# scaffold-digest: eafbee5be9f277db80e7d15f2011fbbb96962a0c05d4bc9863b0fde8761a0cfe

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Splits do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /split as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/split")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /split as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/split")
        .to_return(ok)

      response = resource.create(
        name: "sample_name",
        type: "percentage",
        subaccounts: [{"subaccount" => "ACCT_6uujpqtzmnufzkw", "share" => 50}],
        currency: "NGN"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires name" do
      expect do
        resource.create(
          type: "percentage",
          subaccounts: [{"subaccount" => "ACCT_6uujpqtzmnufzkw", "share" => 50}],
          currency: "NGN"
        )
      end.to raise_error(ArgumentError, /name/)
    end
  end

  describe "#fetch" do
    it "sends GET /split/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/split/1")
        .to_return(ok)

      response = resource.fetch(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /split/{id} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/split/sample_id")
        .to_return(ok)

      response = resource.update(id: "sample_id")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#add_subaccount" do
    it "sends POST /split/{id}/subaccount/add as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/split/1/subaccount/add")
        .to_return(ok)

      response = resource.add_subaccount(id: 1, subaccount: "sample_subaccount", share: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires subaccount" do
      expect do
        resource.add_subaccount(id: 1, share: 1)
      end.to raise_error(ArgumentError, /subaccount/)
    end
  end

  describe "#remove_subaccount" do
    it "sends POST /split/{id}/subaccount/remove as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/split/1/subaccount/remove")
        .to_return(ok)

      response = resource.remove_subaccount(id: 1, subaccount: "sample_subaccount")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires subaccount" do
      expect do
        resource.remove_subaccount(id: 1)
      end.to raise_error(ArgumentError, /subaccount/)
    end
  end
end
