# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Storefront`.
# scaffold-digest: 6a7cd809e102119d6bdc1842609d2ad7c4ab21aedfc22a3bebd41f4ede258b3c

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Storefronts do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /storefront as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/storefront")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /storefront as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/storefront")
        .to_return(ok)

      response = resource.create(name: "sample_name", slug: "sample_slug", currency: "GHS")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires name" do
      expect do
        resource.create(slug: "sample_slug", currency: "GHS")
      end.to raise_error(ArgumentError, /name/)
    end
  end

  describe "#fetch" do
    it "sends GET /storefront/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/storefront/1")
        .to_return(ok)

      response = resource.fetch(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /storefront/{id} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/storefront/1")
        .to_return(ok)

      response = resource.update(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#delete" do
    it "sends DELETE /storefront/{id} as Paystack documents it" do
      stub = stub_request(:delete, "https://api.paystack.co/storefront/1")
        .to_return(ok)

      response = resource.delete(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#verify_slug" do
    it "sends GET /storefront/verify/{slug} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/storefront/verify/sample_slug")
        .to_return(ok)

      response = resource.verify_slug(slug: "sample_slug")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#fetch_orders" do
    it "sends GET /storefront/{id}/order as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/storefront/1/order")
        .to_return(ok)

      response = resource.fetch_orders(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#list_products" do
    it "sends GET /storefront/{id}/product as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/storefront/1/product")
        .to_return(ok)

      response = resource.list_products(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#add_products" do
    it "sends POST /storefront/{id}/product as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/storefront/1/product")
        .to_return(ok)

      response = resource.add_products(id: 1, products: [1])

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires products" do
      expect do
        resource.add_products(id: 1)
      end.to raise_error(ArgumentError, /products/)
    end
  end

  describe "#publish" do
    it "sends POST /storefront/{id}/publish as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/storefront/1/publish")
        .to_return(ok)

      response = resource.publish(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#duplicate" do
    it "sends POST /storefront/{id}/duplicate as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/storefront/1/duplicate")
        .to_return(ok)

      response = resource.duplicate(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
