# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Subaccount`.
# scaffold-digest: 9d5a3e8d8e12166f2c7d8a64f84d260c25284b5b2488410cf1e6a384e0bb5812

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Subaccounts do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /subaccount as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/subaccount")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /subaccount as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/subaccount")
        .to_return(ok)

      response = resource.create(
        business_name: "sample_business_name",
        bank_code: "sample_bank_code",
        account_number: "sample_account_number",
        percentage_charge: 1.5
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires business_name" do
      expect do
        resource.create(
          bank_code: "sample_bank_code",
          account_number: "sample_account_number",
          percentage_charge: 1.5
        )
      end.to raise_error(ArgumentError, /business_name/)
    end
  end

  describe "#fetch" do
    it "sends GET /subaccount/{code} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/subaccount/sample_code")
        .to_return(ok)

      response = resource.fetch(id_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /subaccount/{code} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/subaccount/sample_code")
        .to_return(ok)

      response = resource.update(id_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
