# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Subscription`.
# scaffold-digest: af32eef900b65d596bf2ea6cb786d02b313795ee9053aa20b45b46d2a73e41bc

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Subscriptions do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /subscription as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/subscription")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /subscription as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/subscription")
        .to_return(ok)

      response = resource.create(customer: "sample_customer", plan: "sample_plan")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires customer" do
      expect do
        resource.create(plan: "sample_plan")
      end.to raise_error(ArgumentError, /customer/)
    end
  end

  describe "#fetch" do
    it "sends GET /subscription/{code} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/subscription/sample_code")
        .to_return(ok)

      response = resource.fetch(id_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#disable" do
    it "sends POST /subscription/disable as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/subscription/disable")
        .to_return(ok)

      response = resource.disable(code: "sample_code", token: "sample_token")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires code" do
      expect do
        resource.disable(token: "sample_token")
      end.to raise_error(ArgumentError, /code/)
    end
  end

  describe "#enable" do
    it "sends POST /subscription/enable as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/subscription/enable")
        .to_return(ok)

      response = resource.enable(code: "sample_code", token: "sample_token")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires code" do
      expect do
        resource.enable(token: "sample_token")
      end.to raise_error(ArgumentError, /code/)
    end
  end

  describe "#generate_update_link" do
    it "sends GET /subscription/{code}/manage/link as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/subscription/sample_code/manage/link")
        .to_return(ok)

      response = resource.generate_update_link(code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#send_update_link" do
    it "sends POST /subscription/{code}/manage/email as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/subscription/sample_code/manage/email")
        .to_return(ok)

      response = resource.send_update_link(code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
