# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Terminal`.
# scaffold-digest: 69108704121a91beb7e237d9a024a76d7421713039a2262c5f765c1fb94c2f65

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Terminals do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#send_event" do
    it "sends POST /terminal/{id}/event as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/terminal/sample_id/event")
        .to_return(ok)

      response = resource.send_event(terminal_id: "sample_id")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#fetch_event_status" do
    it "sends GET /terminal/{terminal_id}/event/{event_id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/terminal/sample_terminal_id/event/sample_event_id")
        .to_return(ok)

      response = resource.fetch_event_status(
        terminal_id: "sample_terminal_id",
        event_id: "sample_event_id"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#fetch_status" do
    it "sends GET /terminal/{terminal_id}/presence as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/terminal/sample_terminal_id/presence")
        .to_return(ok)

      response = resource.fetch_status(terminal_id: "sample_terminal_id")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#list" do
    it "sends GET /terminal as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/terminal")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#fetch" do
    it "sends GET /terminal/{terminal_id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/terminal/sample_terminal_id")
        .to_return(ok)

      response = resource.fetch(terminal_id: "sample_terminal_id")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /terminal/{terminal_id} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/terminal/sample_terminal_id")
        .to_return(ok)

      response = resource.update(terminal_id: "sample_terminal_id")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#commission" do
    it "sends POST /terminal/commission_device as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/terminal/commission_device")
        .to_return(ok)

      response = resource.commission(serial_number: "sample_serial_number")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires serial_number" do
      expect do
        resource.commission
      end.to raise_error(ArgumentError, /serial_number/)
    end
  end

  describe "#decommission" do
    it "sends POST /terminal/decommission_device as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/terminal/decommission_device")
        .to_return(ok)

      response = resource.decommission(serial_number: "sample_serial_number")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires serial_number" do
      expect do
        resource.decommission
      end.to raise_error(ArgumentError, /serial_number/)
    end
  end
end
