# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Transfer Recipient`.
# scaffold-digest: 2d1a0641bcb4876a0c8adb89613fcf5b233ef042ad4813b1ee1f4c670176cddf

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::TransferRecipients do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /transferrecipient as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transferrecipient")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#list filters" do
    it "sends per_page as perPage and next_cursor as next" do
      stub = stub_request(:get, "https://api.paystack.co/transferrecipient")
        .with(query: {"perPage" => "2", "page" => "3", "use_cursor" => "true", "next" => "abc"})
        .to_return(ok)

      resource.list(per_page: 2, page: 3, use_cursor: true, next_cursor: "abc")

      expect(stub).to have_been_requested
    end

    it "rejects from and to, which Paystack documents but ignores" do
      expect { resource.list(from: "2026-01-01") }.to raise_error(ArgumentError, /from/)
    end
  end

  describe "#update body" do
    it "sends only the fields given, so email alone is accepted" do
      stub = stub_request(:put, "https://api.paystack.co/transferrecipient/RCP_1")
        .with(body: {email: "ama@example.com"}.to_json)
        .to_return(ok)

      resource.update(id_or_code: "RCP_1", email: "ama@example.com")

      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "rejects an unknown type before any request" do
      expect do
        resource.create(type: "cash", name: "n", account_number: "1", bank_code: "044")
      end.to raise_error(PaystackSdk::InvalidValueError, /type/)
    end

    it "sends POST /transferrecipient as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transferrecipient")
        .to_return(ok)

      response = resource.create(
        type: "nuban",
        name: "sample_name",
        account_number: "sample_account_number",
        bank_code: "sample_bank_code"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires type" do
      expect do
        resource.create(
          name: "sample_name",
          account_number: "sample_account_number",
          bank_code: "sample_bank_code"
        )
      end.to raise_error(ArgumentError, /type/)
    end
  end

  describe "#bulk_create" do
    it "sends POST /transferrecipient/bulk as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transferrecipient/bulk")
        .to_return(ok)

      response = resource.bulk_create(
        batch: [{"type" => "nuban", "name" => "Smith Taplo", "account_number" => "01000000010", "bank_code" => "058"}]
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires batch" do
      expect do
        resource.bulk_create
      end.to raise_error(ArgumentError, /batch/)
    end
  end

  describe "#fetch" do
    it "sends GET /transferrecipient/{id_or_code} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transferrecipient/sample_code")
        .to_return(ok)

      response = resource.fetch(id_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /transferrecipient/{id_or_code} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/transferrecipient/sample_code")
        .to_return(ok)

      response = resource.update(id_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#delete" do
    it "sends DELETE /transferrecipient/{id_or_code} as Paystack documents it" do
      stub = stub_request(:delete, "https://api.paystack.co/transferrecipient/sample_code")
        .to_return(ok)

      response = resource.delete(id_or_code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
