# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d), then
# edited by hand (`fetch(id_or_code:)` and exact wire assertions), so the scaffold will not regenerate it.

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Transfers do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /transfer as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transfer")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /transfer as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transfer")
        .to_return(ok)

      response = resource.create(
        amount: 1,
        recipient: "sample_recipient",
        reference: "sample-reference",
        source: "sample_source"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires amount" do
      expect do
        resource.create(
          recipient: "sample_recipient",
          reference: "sample-reference",
          source: "sample_source"
        )
      end.to raise_error(ArgumentError, /amount/)
    end
  end

  describe "#finalize" do
    it "sends POST /transfer/finalize_transfer as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transfer/finalize_transfer")
        .to_return(ok)

      response = resource.finalize(transfer_code: "sample_transfer_code", otp: "sample_otp")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires transfer_code" do
      expect do
        resource.finalize(otp: "sample_otp")
      end.to raise_error(ArgumentError, /transfer_code/)
    end
  end

  describe "#bulk_create" do
    it "sends POST /transfer/bulk as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transfer/bulk")
        .to_return(ok)

      response = resource.bulk_create(
        source: "sample_source",
        transfers: [{"amount" => 120000, "recipient" => "RCP_gd9vgag7n5lr5ix", "reference" => "acv_9ee55786-2323-4760-98e2-6380c9cb3f68"}]
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires source" do
      expect do
        resource.bulk_create(
          transfers: [{"amount" => 120000, "recipient" => "RCP_gd9vgag7n5lr5ix", "reference" => "acv_9ee55786-2323-4760-98e2-6380c9cb3f68"}]
        )
      end.to raise_error(ArgumentError, /source/)
    end
  end

  describe "#fetch" do
    it "sends GET /transfer/{code} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transfer/TRF_v5tip3zx8nna9o78")
        .to_return(ok)

      response = resource.fetch(id_or_code: "TRF_v5tip3zx8nna9o78")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#verify" do
    it "sends GET /transfer/verify/{reference} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transfer/verify/sample-reference")
        .to_return(ok)

      response = resource.verify(reference: "sample-reference")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#export" do
    it "sends GET /transfer/export as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transfer/export")
        .to_return(ok)

      response = resource.export

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#resend_otp" do
    it "sends POST /transfer/resend_otp as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transfer/resend_otp")
        .to_return(ok)

      response = resource.resend_otp(transfer_code: "sample_transfer_code", reason: "disable_otp")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires transfer_code" do
      expect do
        resource.resend_otp(reason: "disable_otp")
      end.to raise_error(ArgumentError, /transfer_code/)
    end
  end

  describe "#disable_otp" do
    it "sends POST /transfer/disable_otp as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transfer/disable_otp")
        .to_return(ok)

      response = resource.disable_otp

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#finalize_disable_otp" do
    it "sends POST /transfer/disable_otp_finalize as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transfer/disable_otp_finalize")
        .to_return(ok)

      response = resource.finalize_disable_otp(otp: "sample_otp")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires otp" do
      expect do
        resource.finalize_disable_otp
      end.to raise_error(ArgumentError, /otp/)
    end
  end

  describe "#enable_otp" do
    it "sends POST /transfer/enable_otp as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transfer/enable_otp")
        .to_return(ok)

      response = resource.enable_otp

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "exact wire shapes" do
    it "sends create's body with Paystack's names and no unset fields" do
      stub = stub_request(:post, "https://api.paystack.co/transfer")
        .with(body: {
          source: "balance",
          amount: 100_000,
          recipient: "RCP_gd9vgag7n5lr5ix",
          reference: "acv_9ee55786-2323-4760-98e2-6380c9cb3f68",
          reason: "Bonus for the week"
        })
        .to_return(ok)

      resource.create(
        source: "balance",
        amount: 100_000,
        recipient: "RCP_gd9vgag7n5lr5ix",
        reference: "acv_9ee55786-2323-4760-98e2-6380c9cb3f68",
        reason: "Bonus for the week"
      )

      expect(stub).to have_been_requested
    end

    it "requires reference on create, as the docs and the spec do" do
      expect do
        resource.create(source: "balance", amount: 100_000, recipient: "RCP_gd9vgag7n5lr5ix")
      end.to raise_error(ArgumentError, /reference/)
    end

    it "refuses a blank reference before any request" do
      expect do
        resource.create(source: "balance", amount: 100_000, recipient: "RCP_gd9vgag7n5lr5ix", reference: "")
      end.to raise_error(PaystackSdk::MissingParamError)
      expect(a_request(:any, /api\.paystack\.co/)).not_to have_been_made
    end

    it "refuses an unknown currency before any request" do
      expect do
        resource.create(
          source: "balance",
          amount: 100_000,
          recipient: "RCP_gd9vgag7n5lr5ix",
          reference: "acv_9ee55786-2323-4760-98e2-6380c9cb3f68",
          currency: "USD"
        )
      end.to raise_error(PaystackSdk::InvalidValueError)
      expect(a_request(:any, /api\.paystack\.co/)).not_to have_been_made
    end

    it "sends list filters as perPage, page and a numeric recipient" do
      stub = stub_request(:get, "https://api.paystack.co/transfer")
        .with(query: {"perPage" => "20", "page" => "2", "recipient" => "56824902", "from" => "2025-01-01"})
        .to_return(ok)

      resource.list(per_page: 20, page: 2, recipient: 56824902, from: "2025-01-01")

      expect(stub).to have_been_requested
    end

    it "sends the cursor as next" do
      stub = stub_request(:get, "https://api.paystack.co/transfer")
        .with(query: {"use_cursor" => "true", "next" => "abc123"})
        .to_return(ok)

      resource.list(use_cursor: true, next_cursor: "abc123")

      expect(stub).to have_been_requested
    end

    it "sends bulk transfers as given" do
      transfers = [
        {amount: 20_000, reference: "acv_2627bbfe-1a2a-4a1a-8d0e-9d2ee6c31496", reason: "Bonus", recipient: "RCP_gd9vgag7n5lr5ix"}
      ]
      stub = stub_request(:post, "https://api.paystack.co/transfer/bulk")
        .with(body: {source: "balance", transfers: transfers, currency: "NGN"})
        .to_return(ok)

      resource.bulk_create(source: "balance", transfers: transfers, currency: "NGN")

      expect(stub).to have_been_requested
    end

    it "sends no body to disable_otp and enable_otp" do
      disable = stub_request(:post, "https://api.paystack.co/transfer/disable_otp")
        .with { |request| request.body.to_s.empty? }
        .to_return(ok)
      enable = stub_request(:post, "https://api.paystack.co/transfer/enable_otp")
        .with { |request| request.body.to_s.empty? }
        .to_return(ok)

      resource.disable_otp
      resource.enable_otp

      expect(disable).to have_been_requested
      expect(enable).to have_been_requested
    end

    it "refuses a resend_otp reason outside the spec's enum" do
      expect do
        resource.resend_otp(transfer_code: "TRF_vsyqdmlzble3uii", reason: "other")
      end.to raise_error(PaystackSdk::InvalidValueError)
    end
  end
end
