# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Transaction`.
# scaffold-digest: 4411aeb07f2e31edf4a6c782b4a1f07f44d573142a86659ef7cfefec43b54aac

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::Transactions do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#initiate" do
    it "sends POST /transaction/initialize as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transaction/initialize")
        .to_return(ok)

      response = resource.initiate(email: "ama@example.com", amount: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires email" do
      expect do
        resource.initiate(amount: 1)
      end.to raise_error(ArgumentError, /email/)
    end
  end

  describe "#charge_authorization" do
    it "sends POST /transaction/charge_authorization as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transaction/charge_authorization")
        .to_return(ok)

      response = resource.charge_authorization(
        email: "ama@example.com",
        amount: 1,
        authorization_code: "sample_authorization_code"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires email" do
      expect do
        resource.charge_authorization(amount: 1, authorization_code: "sample_authorization_code")
      end.to raise_error(ArgumentError, /email/)
    end
  end

  describe "#partial_debit" do
    it "sends POST /transaction/partial_debit as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/transaction/partial_debit")
        .to_return(ok)

      response = resource.partial_debit(
        email: "ama@example.com",
        amount: 1,
        authorization_code: "sample_authorization_code",
        currency: "GHS"
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires email" do
      expect do
        resource.partial_debit(
          amount: 1,
          authorization_code: "sample_authorization_code",
          currency: "GHS"
        )
      end.to raise_error(ArgumentError, /email/)
    end
  end

  describe "#verify" do
    it "sends GET /transaction/verify/{reference} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transaction/verify/sample-reference")
        .to_return(ok)

      response = resource.verify(reference: "sample-reference")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#list" do
    it "sends GET /transaction as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transaction")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#fetch" do
    it "sends GET /transaction/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transaction/1")
        .to_return(ok)

      response = resource.fetch(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#timeline" do
    it "sends GET /transaction/timeline/{id} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transaction/timeline/1")
        .to_return(ok)

      response = resource.timeline(id: 1)

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#totals" do
    it "sends GET /transaction/totals as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transaction/totals")
        .to_return(ok)

      response = resource.totals

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#export" do
    it "sends GET /transaction/export as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/transaction/export")
        .to_return(ok)

      response = resource.export

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end
end
