# frozen_string_literal: true

# Generated by bin/paystack-scaffold from Paystack's OpenAPI spec (PaystackOSS/openapi@d9d444d).
# Do not edit by hand: regenerate it with `bin/paystack-scaffold Virtual Terminal`.
# scaffold-digest: dc105459adf451f9ec22f48173a9b0cd10d0ca16e12290d3a1e53d90c9a9b0d8

# Wire-shape specs: each sends a real request through the resource.
# spec/support/paystack_contract.rb checks every request against Paystack's OpenAPI spec,
# so these also prove the request conforms.
RSpec.describe PaystackSdk::Resources::VirtualTerminals do
  let(:resource) { described_class.new(secret_key: "sk_test_x", max_retries: 0) }
  let(:ok) do
    {
      status: 200,
      headers: {"Content-Type" => "application/json"},
      body: {status: true, message: "ok", data: {}}.to_json
    }
  end

  describe "#list" do
    it "sends GET /virtual_terminal as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/virtual_terminal")
        .to_return(ok)

      response = resource.list

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#create" do
    it "sends POST /virtual_terminal as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/virtual_terminal")
        .to_return(ok)

      response = resource.create(
        name: "sample_name",
        destinations: [{"target" => "sample_target", "name" => "sample_name"}]
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires name" do
      expect do
        resource.create(destinations: [{"target" => "sample_target", "name" => "sample_name"}])
      end.to raise_error(ArgumentError, /name/)
    end
  end

  describe "#fetch" do
    it "sends GET /virtual_terminal/{code} as Paystack documents it" do
      stub = stub_request(:get, "https://api.paystack.co/virtual_terminal/sample_code")
        .to_return(ok)

      response = resource.fetch(code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#update" do
    it "sends PUT /virtual_terminal/{code} as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/virtual_terminal/sample_code")
        .to_return(ok)

      response = resource.update(code: "sample_code", name: "sample_name")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires name" do
      expect do
        resource.update(code: "sample_code")
      end.to raise_error(ArgumentError, /name/)
    end
  end

  describe "#deactivate" do
    it "sends PUT /virtual_terminal/{code}/deactivate as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/virtual_terminal/sample_code/deactivate")
        .to_return(ok)

      response = resource.deactivate(code: "sample_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end
  end

  describe "#assign_destination" do
    it "sends POST /virtual_terminal/{code}/destination/assign as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/virtual_terminal/sample_code/destination/assign")
        .to_return(ok)

      response = resource.assign_destination(
        code: "sample_code",
        destinations: [{"target" => "sample_target", "name" => "sample_name"}]
      )

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires destinations" do
      expect do
        resource.assign_destination(code: "sample_code")
      end.to raise_error(ArgumentError, /destinations/)
    end
  end

  describe "#unassign_destination" do
    it "sends POST /virtual_terminal/{code}/destination/unassign as Paystack documents it" do
      stub = stub_request(:post, "https://api.paystack.co/virtual_terminal/sample_code/destination/unassign")
        .to_return(ok)

      response = resource.unassign_destination(code: "sample_code", targets: ["sample_targets"])

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires targets" do
      expect do
        resource.unassign_destination(code: "sample_code")
      end.to raise_error(ArgumentError, /targets/)
    end
  end

  describe "#add_split_code" do
    it "sends PUT /virtual_terminal/{code}/split_code as Paystack documents it" do
      stub = stub_request(:put, "https://api.paystack.co/virtual_terminal/sample_code/split_code")
        .to_return(ok)

      response = resource.add_split_code(code: "sample_code", split_code: "sample_split_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires split_code" do
      expect do
        resource.add_split_code(code: "sample_code")
      end.to raise_error(ArgumentError, /split_code/)
    end
  end

  describe "#remove_split_code" do
    it "sends DELETE /virtual_terminal/{code}/split_code as Paystack documents it" do
      stub = stub_request(:delete, "https://api.paystack.co/virtual_terminal/sample_code/split_code")
        .to_return(ok)

      response = resource.remove_split_code(code: "sample_code", split_code: "sample_split_code")

      expect(response).to be_success
      expect(stub).to have_been_requested
    end

    it "requires split_code" do
      expect do
        resource.remove_split_code(code: "sample_code")
      end.to raise_error(ArgumentError, /split_code/)
    end
  end
end
